### ISSUE TITLE
v3.917 Browse RLV folders shown as [number]??

### ISSUE THREAD

**Issue by napilisands** [OpenCollar/opencollar#10]
When browsing RLV folders, ?? is displayed instead of state check boxes.

After updating from 3.910, state check boxes are displayed as question marks.
Item numbers are still displayed.

e.g. 
"0 ??Ball Gag"
"1 ??Lockable Panel Gag"

3.916 also did the same.

**Comment by WendyStarfall** [comment]
we have it fixed in the beta branch and will be able to have a new release for the main channel soon; I still don't know how the ascii characters got lost in those versions, probably external editor gobbled them but oh well, it's fixed in the beta
