### ISSUE TITLE
Bookmarks on Sim names that include a space fail to link properly in chat.

### ISSUE THREAD

**Issue by Mace68** [OpenCollar/opencollar#1008]
My guess would be that the slurl should be urlencoded before printing to chat.

**Comment by Mace68** [comment]
I fixed mine, not sure if it's the best way but I changed line 417 from
`llOwnerSay("Follow your Partner(s) right way by clicking here: secondlife:///app/teleport/"+g_sRegion+sPos);`
to
`llOwnerSay("Follow your Partner(s) right way by clicking here: secondlife:///app/teleport/"+llEscapeURL(g_sRegion+sPos));`

**Comment by WendyStarfall** [comment]
Hi Mace68, thanks for pointing that out! I'm travelling at the moment but I hope that I can take a look at it later. Maybe you could attach a pull-request to the issue? It's pretty straight-forward, I will show you how:

1. Go there > https://github.com/VirtualDisgrace/opencollar/edit/master/src/remote/oc_remote_bookmarks.lsl

2. Make your edit right there in the code.

3. Move you focus outside of the edit code form and scroll down to do this:

![2017-02-06_0647](https://cloud.githubusercontent.com/assets/1100007/22636021/86b98b4a-ec38-11e6-881c-1059a18deb0d.png)

All the relevant stuff is filled out automatically. For you it will say 'Mac68-patch-1' and that's perfect. Once you click 'Propose file change' it will fork the project to your account, create a patch branch and attach it as a pull-request to our upstream. Yay! 🍰

**Comment by WendyStarfall** [comment]
Fixed by @Mace68 with PR #1009 
Thank you! ❤️ 

> What happens next?
> 
> We are going to keep the issue open with the [fixed] label until the next version of the Remote is compiled and shipped in-world. When the issue closes, it gets filed away in the 6.4 Milestone. We use the Milestones as our changelogs and link them in the print that happens after successful updates.
