### ISSUE TITLE
Themes: Ability to uninstall with command

### ISSUE THREAD

**Issue by WendyStarfall** [OpenCollar/opencollar#1041]
**Version:** ``6.5.5``

With the stealth logic separate to ``oc_themes`` we no longer require the plugin to be in every device.

I suggest that instead of printing the notify that we currently receive when no ``.themes`` card was found, we rather serve a menu with informational text in the prompt and three options ``Uninstall | Looks | BACK``

**Comment by GarvinTwine** [comment]
Todo: informal text in the dialog looks not nice...
