### ISSUE TITLE
Blacklist options in RLVsys or RLVRelay

### ISSUE THREAD

**Issue by Davwyn** [OpenCollar/opencollar#1042]
Would it be possible for soft-core users to have a function in the OpenCollar RLV scripts to refuse specific RLV commands such as blockIMs or blind?

Editing the collar itself isn't too hard to remove such commands, but when using an RLV trap item it's very difficult to find a way to forbid it. Some clients like CatNipz the viewer itself allows you to blacklist some RLVa commands but most clients like Firestorm lack this viewer function.

It could be made so the collar warns owners of any disabled functions so they're aware their pet isn't fully restrictable.

I just discovered this, but in the documentation http://wiki.secondlife.com/wiki/LSL_Protocol/RestrainedLoveAPI#List_of_commands

There is for example @getblacklist  This of course is for viewer-level blacklist. But I figure a script-level blacklist filter can be made in a similar fashion.

**Comment by WendyStarfall** [comment]
I'd modify ``oc_rlvsys`` to suit my particular needs in this case.

The script needs memory to do its job, so adding some kind of blacklist for RLV commands, and making it so that authorized Owners can conveniently adjust, would inevitably require another plugin. In that case, you'd have to run all RLV commands through this "catalyst plugin" prior to sending them to ``oc_rlvsys``.

Sounds like a fun hobby project! (not volunteering) 🙊

**Comment by Davwyn** [comment]
Oh, I completely forgot that there could be memory limitations. However I was thinking these blacklist settings were set by the wearer (However the owner would be aware what the blacklist is) to function basically the same way the Viewer blacklist should work but for viewers that still lack this feature.

Going through the list of all RLVa functions that could be set. There's something in that list just about anybody might object to using.

**Comment by WendyStarfall** [comment]
I really meant it when I said that it could be a fun project. I just have my hands full with stock release stuff.

It would be more fun to modify ``oc_relay`` and add some kind of filter or "catalyst" plugin. The relay gets its commands, passes it through the filter plugin, which passes all allowed commands further to ``oc_rlvsys``.

There will be challenges to make it work snappy and robust. If you want to do this in nightmare mode, you could modify ``oc_rlvsys`` directly, but there will be no space then for a user friendly menu that owners can work with for blacklist or whitelisting commands.

**Comment by Davwyn** [comment]
Yah. It'll very much be a challenge. I barely know enough about LSL to edit existing code, let alone write new functions or entire scripts. What little programming experience I have is LUA, BASH, and starting PowerShell. If anyone is interested in this, you have my kudos. I'll direct some programmer friends at this in case any are interested.
