### ISSUE TITLE
titler script deletes if prim has highest link number

### ISSUE THREAD

**Issue by xxReyes** [OpenCollar/opencollar#1054]
Not sure if this is intentional or not but if the floattext prim has the highest link value in the linkset then the oc_titler script self deletes with no message stating why. This seems to be due to line 247 where we are checking each prim and counting down however for some reason we stop counting if linkNumber is higher that 2 which stops the check before all of the prims have been inspected; I modified that line to stop if >0 and that seems to correct the issue.

        while (linkNumber-- >2){

If there is some particular reason we stop the counting at >2 and this isn't a bug then it would be a good idea to update the website notes so we know not to select the floattext prim first when linking the collar.

**Comment by WendyStarfall** [comment]
To the best of my knowledge, ``linkNumber`` refers to the counted amount of links. not the number that the link gets assigned in the particular link-set. It seems to me though that you are using a different source than ours. We are a bit more builder friendly and do the following in this case:

``
if (~llSubStringIndex(sLowerStr,"title") && g_iTextPrim == -10) {
        Dialog(kAv,"\n[http://www.opencollar.at/titler.html Titler]\t"+g_sAppVersion+"\n\nThis %DEVICETYPE% is missing a FloatText element which is required to display and to adjust titles. Please visit [http://www.opencollar.at/titler.html this page] to learn how to add this element to your %DEVICETYPE% or click [Uninstall] below to remove the app.",["Uninstall"], [UPMENU],0, iAuth,"main");
        return;
``

When the user selects ``[Uninstall]``, only then the script gets removed.

**Comment by xxReyes** [comment]
the linkNumber variable in that context is being decremented as a counter in a loop and the script appears to be checking to see if any of the prims has the appropriate "FloatText" description - The problem appears to be that this counter doesn't count all the way down to 1, it is stopped when the counter is >2 so once it reaches the next to last link number it stops; changing that specific line from >2 to >1 prevents this from happening.

**Comment by WendyStarfall** [comment]
Prevents what? Not a single device in our collection has the problem that you are trying to describe.

**Comment by GarvinTwine** [comment]
First of all, as Wendy said, the titler script no longer deletes itself at all.
#1039 

Let me try to explain what exactly is done in the script and why.
Linksets with more than one prim have the links numbered, started with the root prim as 1 and counting up to the last one. 
The loop that looks for a certain prim should check all link numbers > 1 (as 1 is always root and should never be the one looked for).
The loop in the titler script does it this way:
`
integer iLinkNum = llGetNumberOfPrims() + 1;
while (iLinkNum-- > 2 )
  { code to check and set in here }
`
This means iLinkNum becomes the highest link number in the first loop:
the number all prims + 1 and then - 1 so again that number...
then it gets counted down until iLinkNum is 2 (which would check in the code for the link # 1 which is root and we do not need to check).
So the way it is done here is for sure not the only way and you can argue if it is the best way but in any way it is a way that works and covers all prims in a linkset but the root itself (which never should be the floattext prim anyway).
So the only way you get an issue here is when you want to use the root of your linkset as floattext prim, and that is to prevent by the script and that is indeed intended!
And exactly this seems to be what you do when you say "highest prim number" but then it fails when it does not use link number 1, because the last prim you link the linkset to, becomes root.

I hope this clarifies things and I think we can close this :)

**Comment by xxReyes** [comment]
The script self deletes silently; this is using the scripts from 6.6.0 in a custom caller; in this case it was a mesh collar where i had linked 6 invisible prims (RLV, Authenticator,Settings,FloatText...) plus the mesh prim that was the visible portion of the collar;  the logic i referenced is a loop that is checking to see if the prim exists that has the 'FloatText" description. 

When linking these 7 prims I had selected 'FloatText" first and the root prim last (the last prim selected when linking becomes the root prim of the linkset). The FloatText prim became "Link Number 7" as far as the link numbers in the linkset are concerned. in that specific scenario whenever I dropped the oc_titler script into the root prim it immediately self deleted. 

Modifying that specific line from >2 to >0 prevented the titler script from self deleting; with that one change i could set titles properly. - A workaround which also worked was to relink the linkset so that the FloatText was not the highest numbered link in the linkset.

**Comment by xxReyes** [comment]
ok; I just compared the scripts between the collar that i got from the temple yesterday with the code on github and the oc_titler script that came with those collars has 3 instances of the llRemoveInventory call (one of which is in line 261 immediately after this logic runs) - that line is removed in the code currently on the github site so the latest code may very well fix this issue.

**Comment by xxReyes** [comment]
As I noted in my comment to Garvin I was using the code directly from one of the collars from the main temple which is reported to be 6.6.0; the code is NOT the same as the code on GITHUB as there is an llRemoveInventory call in line 261 of the code in the 6.6.0 collars that does not appear in the github code. 

According to the defect ( https://github.com/VirtualDisgrace/opencollar/issues/1039 ) that Garvin mentioned this code change occurred in version 6.5.5 so I don't know why the 6.6.0 collars do not have that change. - I have just checked 2 other brand new collars from the Temple and they both had the oc_titler script that results in the behavior I described.

**Comment by WendyStarfall** [comment]
I build with production ready source that works for our collection, and the titler works fine in every device that you get from us. So does the titler plugin that I provide in an installer with Legacy Apps bundles, that uses the more builder friendly source, which is better suited to be supplied as an individual plugin.

I don't need extra logic for builders in production source for my products, when those are already built. It is here, in the source code on GitHub, and it is also in the titler plugin that you can pick up at our place in SL.

I understand that you seem to have problems creating your own build, and everyone is welcome to ask for advice, but there is no reason to prompt redundant edits or to suggest us to alter our documentation in some way if you fail to build something, when you aren't even building but recycling another device.

**Comment by GarvinTwine** [comment]
Just to clarify:
I did not mention a defect or anything and neither does #1039, there was no defect in the titler script that is delivered within the collars at the temple.
#1039 just handles the missing FloatText prim different but the logic to detect it has not changed at all, the functionality of the script did not change.
I test the last 4 weeks with a collar that happens also to have the FloatText prim as its last prim (highest number) in its linkset and did not run once into the issue that it was not detected as you describe.
