### ISSUE TITLE
Make Vanilla a "real" mode: more tasty, less calories

### ISSUE THREAD

**Issue by GarvinTwine** [OpenCollar/opencollar#1058]
Yes, lets make Vanilla (or any flavor you prefer, as you can change it)

> prefix flavor strawberry

a real mode rather than just adding the wearer to the owners-list.

#### What are the benefits?

1. This allows one more owner while vanilla is enabled
2. This solves an unwanted side-effect in the rlv-relay ask mode.
    Current behavior: With Vanilla turned on the wearer is added to the owner-list, and objects, such as furniture or rlv traps, that are owned by the wearer are automatically sent through the rlv relay even in ask mode, because the object is trusted as it belongs to a listed owner. With the new "real" vanilla mode, this does not happen any more because the wearer is not part of the owner-list, just all collar-requests by the wearer get "authed" as owner.

#### What should be done:

Do not add the wearer to the owner-list and set a single boolean value ``g_iVanilla = TRUE/FALSE``.
Leave the commands and menus as they are, so there is no visual change in the user experience.
Menu and command remain as they were:

> prefix vanilla on|off

#### Lets not forget to keep the current vanilla setting where the wearer is part of the owner-list:

During the update process the wearer should be removed from the owner-list and the new setting for vanilla should be stored.

For those who prefer to have vanilla mode configured out of the box, in their .settings card (not recommended but demanded) the entry would be ``AUTH=vanilla~1``

Where as it is now prevented to add the wearer to the owner-list, the "backdoor" using the .settings notecard still works. It won't turn vanilla mode on though, but works just the same just without the benefits of the new vanilla mode and vanilla won't be shown as on.

#### What stays as it is:

Vanilla can be turned on and off only by owners! 
Unowned wearer can turn it on/off.
When your owner (or yourself while owned) turns it off, it is off for you, you cannot turn it on again, then only an owner can!

#### What else?

The collar won't tell you any more that you belong to yourself.
In the Access List print out, it will show the vanilla status.

**Comment by george-black** [comment]
👏👍
