### ISSUE TITLE
Version 6.7  ( and possibly others ) responds incorrectly to a version request.

### ISSUE THREAD

**Issue by vince-br-549** [OpenCollar/opencollar#1068]
I have a product that querys the version number of the user's relay. using the command
"@version=<channel_number>" 
or
"@versionnew=<channel_number>" 
or
"@versionnum=<channel_number>" 

These cause the collar to ask the user  ( assuming ask mode ) for permission to control the users collal

The 6.7 versions and possibly older targets respond with
<my product name> wants to control your viewer do you want to allow it .....

**Comment by vince-br-549** [comment]
Looks like if I send "@Version=<channel_number>"
the collar returns  RLVa 1100
If I send versionnew=< ....>
you return ew,ko
if I send versionnum ... you return
um,ko

I'm looking at the RLVa protocol here
http://wiki.secondlife.com/wiki/LSL_Protocol/RestrainedLoveAPI#Version_Checking

**Comment by vince-br-549** [comment]
Just tested with 6.6.3 the problem is not there.

**Comment by GarvinTwine** [comment]
I am not sure why you use "@version" to query the relay version, the command for that is "!version" in the rlv relay protocol http://wiki.secondlife.com/wiki/LSL_Protocol/Restrained_Love_Relay/Specification#.22.21version.22_meta-command
I am not sure if an ask request for control for that command is something we want to see either though, I will look closer into this.

**Comment by vince-br-549** [comment]
This seems to partially demonstrate the problem.

key agent;
string versionCmd="!version";
integer channel = 0;
default
{
    state_entry()
    {
        llSay(0, "Hello, Avatar!");
    }

    touch_start(integer total_number)
    {
        llSay(0, "Touched.");
        agent = llDetectedKey(0);
         llSay(-1812221819, "locator," +(string)agent + "," + versionCmd + "="+(string)channel);
    }
}


The above re-creates the ask menu dialog.
Been long time since I looked at this,  shouldn't the relay echo the channel number with the above code?

**Comment by GarvinTwine** [comment]
You should only send `!version` as your command `!version=channel` will not be answered.
http://wiki.secondlife.com/wiki/LSL_Protocol/Restrained_Love_Relay/Specification#.22.21version.22_meta-command

But reviewing the relay code I found some things and changed some as well.
So thank you for coming up with this!

**Comment by WendyStarfall** [comment]
Can I build it? 😄

**Comment by GarvinTwine** [comment]
Let's do it
