### ISSUE TITLE
timer is broken: missing real-time and doesn't lock anything

### ISSUE THREAD

**Issue by timberwoof** [OpenCollar/opencollar#107]
The Timer does not work as expected: there's no real-time timer and it applies no RLV locks to anything. 

Setup: 
Obtained brand new tech Collar from an OpenCollar vendor.
Rezzed it and applied the Updater to add the Timer Add-On.
Wore the collar. 

Click Collar, then 
AddOns > Timer > ()Clear RLV, ()Unlock, ()Unleash, Online >  +03:00
Back > Start

In viewer, look at RLVa restrictions list.

Results: No restrictions. 
Expected: The collar should be locked. 

Note: Eva Ryan replicated this bug. (Thanks, Eva!)

**Comment by timberwoof** [comment]
I did this again, but first attached the HUD. 
The resulting restrictions are
RestrainedLove viewer v2.7.0 (RLVa 1.4.8)

Tech Collar (Neck):
  -> detach:bottom

Timberwoof Lupindo's ACS CCU v1.7.0 (Bottom):
  -> emote
  -> notify:87871313;detached
  -> detachallthis:outfits
  -> detachallthis:shapes

Which is as expected with the default settings file containing
User_rlvrelay=settings~mode:138
User_rlvundress=List~detach:Bottom,n

However, I can detach the collar.

**Comment by WendyStarfall** [comment]
is already fixed in the beta with ab8cdec3cde508988f9308432070fa1030fbb171 and bbee5f0df3a343635760fbbc1e1e87ad57819271

**Comment by timberwoof** [comment]
I reviewed the code and it looks like the fix will work.
