### ISSUE TITLE
Minor typo in "README/EULA - Wendy's Distribution"

### ISSUE THREAD

**Issue by stawberri** [OpenCollar/opencollar#1075]
You've probably caught and fixed this already, but I hope you wouldn't mind me bringing this up just in case 😅 

The safeword configuration directions state:

> To do so, type a slash "/" followed by a <space>, followed by your <prefix>, followed by a <space> followed by the command "safeword", followed by a <space> followed by your new <safeword>.
> 
> Here is an example: /1 we safeword Taxi

The first line's directions don't match up with the example. The example has a channel number, while the directions don't.

**Comment by WendyStarfall** [comment]
Thanks for letting me know, I've corrected it in the README, and there is also in the copy on opencollar.at

http://www.opencollar.at/updates.html
