### ISSUE TITLE
Titler graph options

### ISSUE THREAD

**Issue by Saraeva** [OpenCollar/opencollar#1076]
Is it possible to make Titler graph do decimals and fractions? I wanted to make it say "99 44/100% Pure" but, it turned out to be "99% 44/100% Pure". And decimals get dropped altogether. 
can be edited... and edited back to original form too.

**Comment by george-black** [comment]
I hate fractions. I might be able to save the decimals, though :)  I'll see how it feels when I dig into it.

**Comment by YuukieO** [comment]
I noticed one bug with the graph option, looks like the titler cuts off the text after the first word, a title of "100% in love" shows as "100% in"

**Comment by Saraeva** [comment]
@YuukieO I think that's been fixed already. https://gyazo.com/f84538a8c4df4355df898a0ca073b0d1
Might want to grab a new updater and install it again.

**Comment by george-black** [comment]
@YuukieO It has been fixed, but I don't think it's in the Peanut release. It will be in the next update!

https://github.com/WendyStarfall/opencollar/commit/837dde3301b7ecaa1bddb534c441459f413cc157

**Comment by WendyStarfall** [comment]
It's part of Peanut ``Build: 171214.1`` that has been released on the 14th.

Just install another update and it will be fine.

**Comment by YuukieO** [comment]
my collar says it is up to date, but... look at the screenshot: https://gyazo.com/f611ec24a5bf33e80c18bbe3d7e71329

edit: i get my updaters on the SL Marketplace... so I just got a fresh batch and those are fixed!
