### ISSUE TITLE
Trusted limit

### ISSUE THREAD

**Issue by Annaden3** [OpenCollar/opencollar#1078]
For a few hours now, i've been trying to solve a problem i have.

I'm trying to set up my collar, so that i can turn ims off but only get the messages from trusted. I found out that the limit is only 15 people. 

I made a group to try testing if i could read ims from trusted that way and i couldn't.

It's been suggested that i try editing the script to see if i can make the limit bigger, but i can't find anywhere in the scripts that even suggest the limit is 15 in general to be able to change.

Help me before i go insane. I simply need to know, can i change the limit at all, have it changed for me, do i have to leave the ims on or do i simply have to shorten my list of trusted some how?

**Comment by WendyStarfall** [comment]
The limit of trusted avatars is greater on the Peanut releases, you can pick it up at Arcadia.

**Comment by WendyStarfall** [comment]
You can easily change the overall limit at this line of the ``oc_auth`` program:

https://github.com/VirtualDisgrace/opencollar/blob/master/src/collar/oc_auth.lsl#L61

``integer g_iMaxUsers = 60;``

In the current release it is set to 60, I would be cautious to make it much higher than that, but you can experiment of course.

**Comment by Annaden3** [comment]
Thank you.
