### ISSUE TITLE
RLV restrictions disappear after teleport

### ISSUE THREAD

**Issue by timberwoof** [OpenCollar/opencollar#108]
Setup: 
Attach an ACS CCU (a HUD that is a roleplaying aid for robots; it adds RLV restrictions of its own.)
Prepare a Tech Collar by updating and adding the Timer AddOn. 
Set the Tech Collar to lock the ACS CCU HUD. 
Lock the Tech Collar. 
Set a timer on the Tech Collar. 
Verify that the RLVa restrictions are in place: 

RestrainedLove viewer v2.7.0 (RLVa 1.4.8)

Timberwoof Lupindo's ACS CCU v1.7.0 (Bottom):
  -> emote
  -> notify:87871313;detached
  -> detachallthis:shapes
  -> detachallthis:outfits

Tech Collar (Neck):
  -> detach:bottom
  -> detach

Teleport to a bunch of sims. After every teleport, check that the HUD ad the collar cannot be removed. 

Results: after roughly half a dozen teleports (this varies and does not correlate with specific sims), the RLV lock from the collar will fail: 

RestrainedLove viewer v2.7.0 (RLVa 1.4.8)

Timberwoof Lupindo's ACS CCU v1.7.0 (Bottom):
  -> emote
  -> detachallthis:shapes
  -> detachallthis:outfits
  -> notify:87871313;detached

Expected: come hell or high water, keep those RLV locks in place. 
I can detach the collar. 

Note: I reattach the collar and it thinks it is locked (menu says Unlock) and the timer is still running. 
Click Unlock and then Lock restores everything.

**Comment by WendyStarfall** [comment]
connected to #108

**Comment by timberwoof** [comment]
Today with the Timer and Keys modules of Beta 3.954 I tried teleporting 17 times between different sims and was not able to replicate the problem. I will continue to monitor this.
