### ISSUE TITLE
user_text key and content gets name self-concatenated in dump cache

### ISSUE THREAD

**Issue by timberwoof** [OpenCollar/opencollar#109]
Environment: Tech Collar (which has a nice label thing in the front)
Update with "OpenCollarUpdater BETA - 3.954" and Label AddOn.

Setup: 
Use the Label AddOn to set a label. (In the examples to follow, that's Lup-4636.)
Use the Dump Cache feature and make the "defaultsettings" notecard.
Load the defaults. 
Use Dump Cache again (reasonable if other changes have been made).

Results: 
the User__Text entry begins to grow: 
For example, in the first Dump Cache, the line was
User__Text=Text~Lup-4636

In the second Dump Cache, it reported
User__Text_Text_Text_Text=Text_Text_Text_Text~Lup-4636
…
User__Text=Text~Lup-4636

**Comment by ghost** [comment]
it's not OpenCollar scripts bug. 
try delete 'Old Script' from collar and reset all scripts (or only settings and label  scripts to flush text settings)
it's weird, I can't open  'Old script'  : "Second Life: Script is missing from the database."
but it creates these User__Text

**Comment by WendyStarfall** [comment]
That's right, it's coming from the deprecated "techlabel"
