### ISSUE TITLE
3.924 adjust position buttons don't match actual adjustment

### ISSUE THREAD

**Issue by napilisands** [OpenCollar/opencollar#11]
From Appearance, Position:
Backward moves right
Forward moves left
Up moves forward
Down move back
left moves up
right moves down

**Comment by WendyStarfall** [comment]
that depends on the rotation of the root of the specific design; the way it used to be was the the majority of designs did it exactly the wrong way you describe, even the base collar design. to fix this, just rotate the root prim the way it is on the base collar which would be 0, 90, 0

**Comment by CorwinDavidson** [comment]
It has nothing at all to do with the rotation of the root prim unless you are playing with those items on a collar rezzed in world.  It has everything to do with the rotation of the attachment point. Chest, Spine and Neck.. the 3 primary collar attachment points, all have different attachment point rotations.

**Comment by WendyStarfall** [comment]
ah, there you go then, we moved to neck points as "default"

**Comment by SatomiAhn** [comment]
Attachment point can be detected by LSL. This info could be use to modify the behavior of position adjustment buttons.
