### ISSUE TITLE
about  NULL_KEY  in llMessageLinked(LINK_SET, iNum, ........ , NULL_KEY);

### ISSUE THREAD

**Issue by ghost** [OpenCollar/opencollar#110]
I think that there is no need to send NUL_KEY in LM_SETTING_RESPONSE, LM_SETTING_REQUEST, MENUNAME_REQUEST, MENUNAME_RESPONSE ... e.t.c

it is not used, not processed by the "receiver" and only increases link_message flow, CPU time and memory

I think that would be correct to use "" instead NUL_KEY, 
like 
llMessageLinked(LINK_SET, LM_SETTING_RESPONSE, ........ , "");

**Comment by XenHat** [comment]
Is it really worth it? Can you provide some numbers on this?

**Comment by ghost** [comment]
http://wiki.secondlife.com/wiki/NULL_KEY
NULL_KEY is actually string "00000000-0000-0000-0000-000000000000"
why send "long" and unused string, when send empty "" ?

**Comment by XenHat** [comment]
Are you absolutely sure than Auth or getav doesn't uses NULL_KEY to check against real keys?

EDIT: I just checked, they don't. Interesting. Worh a try, I suppose.

**Comment by ghost** [comment]
I'm talking about functions where keys is not used.
such as LM_SETTING_SAVE/REQUEST/RESPONSE/EMPTY  MENUNAME_REQUEST/RESPONSE/REMOVE 

Auth, Getavi, Dialog e.t.c  should used keys (not NULL_KEY) for check avatars/objects/dialogs uuids

I replace NULL_KEY with "" in my OC scripts, and they works fine

**Comment by XenHat** [comment]
yeah, I would assume it to work fine. I can't speak for official people, though, but that's a good thing for future versions

**Comment by XenHat** [comment]
I just opened timer.lsl and I saw this

//      5) DoMenu whatever changed to return on NULL_KEY, in case of
internal calls.

**Comment by ghost** [comment]
it is a double check avatar key for Dialog.
IMHO it's excess check

**Comment by XenHat** [comment]
As far as i'm concerned, I'm fine with it as long as it doesn't break anything. I'm not in charge of anything OC at the moment, though. Wendy said something about "not being the right time to mess with calls", but she seemed to think it would be something to do in the future.

**Comment by WendyStarfall** [comment]
Here is what I could learn from mouse: If we have a train and the train has less passengers, it will not make it smaller. The train still takes up the same space as before. So it is the same with a key, if we put an empty string into it, it will not make the message smaller.

I also learned that it is a sin! (Which makes it oddly attractive for some reason...)

**Comment by littlemousy** [comment]
as Romka pointed out, lsl wiki says "You can use id as a second string field[2]. The sizes of str and id are only limited by available script memory.", so my assumption there was wrong.

My initial thought was that NULL_KEY and empty string shouldn't be mixed, but in this case, it seems the LL are deliberately blurring the lines between the two, so I say go for it.

**Comment by WendyStarfall** [comment]
Let's sin! \o/

**Comment by ghost** [comment]
I think that'll do it later.
it's too much script should be changed

**Comment by ghost** [comment]
Whew, how many of these NULL_KEYS!!!
I need a vacation... and sour cream, meow =^_^=

**Comment by WendyStarfall** [comment]
Thanks Ромка! _pours the cat a big bowl of sour cream_
This issue is closes with the following pulls:

#138 #139 #140 #141 #142 #143 #144 #145 #146 #147 #148 #149 #150 #151 #152 #153 #154 #155 #156 #157 #158 #159 #160 #161 #162 #163 #164 #165 #166 #167 #168 #169 #170
