### ISSUE TITLE
Collar disappears

### ISSUE THREAD

**Issue by collarone** [OpenCollar/opencollar#112]
Even when set to visible, the collar disappears after relogging

**Comment by WendyStarfall** [comment]
That's annoying. Best rez it out on the ground, touch it for the menu. Appearance Hide/Show -> Show Collar. Wait a few seconds, pick it up, put it on, relog and you should be good again.

**Comment by collarone** [comment]
Thank you so much.

On Wednesday, March 12, 2014 12:46 AM, WendyStarfall notifications@github.com wrote:

That's annoying. Best rez it out on the ground, touch it for the menu. Appearance Hide/Show -> Show Collar. Wait a few seconds, pick it up, put it on, relog and you should be good again.
