### ISSUE TITLE
Key Holder Force-Return-Key Bug

### ISSUE THREAD

**Issue by NoriMouse** [OpenCollar/opencollar#14]
Reported by Shana Deed, in-world.

In the manual, it is described that it possible for a Primary Owner to force return the key, if someone else has taken them.
However, when my Master tries that, the nothings happens.
Although the collar is open for him, it is locked to the wearer (in this case, me).
The only way that seems to return the keys, is to turn the AddOn off and then back on.

Also, when you use the Timer AddOn to automatically return the keys, nothing happens either.
When you try to enable the option that returns the keys, the nothing happens, and the collar menu doesn't come back.

**Comment by WendyStarfall** [comment]
while testing, I also learned that RED (safeword) will fail to lift keyholder restrictions or let alone would return the key; this is bad news, I got my crosshairs on keyholder, the safeword must work at all times

**Comment by WendyStarfall** [comment]
I guess the last commit closes that issue. However, keyholder isn't going to be in the main release, I'm going to add it to the blue bundles for 3.930.

**Comment by WendyStarfall** [comment]
safeword is failing again for keyholder as of bbee5f0df3a343635760fbbc1e1e87ad57819271

**Comment by WendyStarfall** [comment]
Closing this, please see 23fe7107c5676d3a11fac64891c3e57bc1510056
