### ISSUE TITLE
OpenCollar - hovertext:   Question: save settings in prim params or in settings DB ?

### ISSUE THREAD

**Issue by ghost** [OpenCollar/opencollar#171]
current version hovertext script save parameters ( text, color, on/off, text position) into prim parameters.
is it good? (in fact, it saves memory for settings).
may be necessary to store them into database?

What do you think?

**Comment by littlemousy** [comment]
I spoke to Wendy about this, We came to the conclusion that storing settings in the DB was better than just on the prim so to settings could be entered onto the default settings notecard.

**Comment by ghost** [comment]
then I need to rewrite the script

**Comment by ghost** [comment]
I did it! #173
