### ISSUE TITLE
Firestorm AO no longer controlled by Collar

### ISSUE THREAD

**Issue by CorwinDavidson** [OpenCollar/opencollar#18]
The Firestorm AO implemented the OC protocol to control the Firestorm AO.  This functionality was removed in 3.9.

http://wiki.phoenixviewer.com/fs_controlling_ao_w_scripts
https://code.google.com/p/opencollar/wiki/OpenCollarAttachmentProtocol

**Comment by WendyStarfall** [comment]
The main channel never had this functionality removed and for the beta we did the interface run from 3.918 to 3.923; that means we had six beta/nightlies for exploring the alternative interface with all of them flagged in the release notes news item that "we want to test and explore the new interface and bring AO/HUD integration back"; in 3.924 we had full compatibility back; the main channel releases weren't affected by that - AO workies! :dancers:
