### ISSUE TITLE
OpenCollar - leash,   about UserCommand()

### ISSUE THREAD

**Issue by ghost** [OpenCollar/opencollar#189]
UserCommand() calls from inside UserCommand()  is not a good idea

**Comment by WendyStarfall** [comment]
I learned that a function can be recursive like 0!=1 and then all n>0 could be n!=n(-1)!
mouse explain that to me with pancakes and a function 'take off all the pancakes' that "takes off one pancake and if there are any pancakes left 'take off all the pancakes'"
