### ISSUE TITLE
Person Finder Handler: Adding oneself

### ISSUE THREAD

**Issue by WendyStarfall** [OpenCollar/opencollar#2]
If someone tries to add themselves on the collar in a region with no other agents present, the person finder handler will not show up the wearer themself as possible owner.

**Comment by NorthGlenwalker** [comment]
I had this problem with the Owners hud as well (yes an owner can wear a collar, I have a ring with rlv dress/undress set) or a single sub in a region would not always see them. no idea how I fixed it.

I tested this on 3 diffent sims where I was the only agent and always it came up as "You are the only person on this sim. Do you wish to add yourself?"

**Comment by SilkieSabra** [comment]
This was always true, i think even before 3.8, you would only show up in the list if there were other names in range also

**Comment by WendyStarfall** [comment]
let's see how it behaves with the final evolution merge, I just finished editing 3.844 for the content upgrade and I'm pretty sure Joy fixed this one as well... everything is fixed there, the rotations problem in 3.911 and the line limit in 3.910 were already fixed in 3.844 too

**Comment by WendyStarfall** [comment]
I'm done for tonight, can no more, released 3.919 on the beta channel and let's see tomorrow if the bug is still present in this version

**Comment by WendyStarfall** [comment]
I haven't been able to reproduce the issue running 3.916 and 3.920, on different simulator versions. Maybe it occurred during the sunshine roll but these two versions are fine. Closing this issue.
