### ISSUE TITLE
Enhancements for the Main Menu

### ISSUE THREAD

**Issue by WendyStarfall** [OpenCollar/opencollar#21]
two more things could be useful for the Main Menu:
1. we want to see the version we are running in the menu text
2. the ℹbutton could be a pop-up menu instead a load webpage menu; we can add links and other "About" information there

some useful snippets I got from the update script regarding version:

``` C#
my_version_request = llGetNotecardLine("~version", 0); 

    else if (llList2String(cmd_parts, 0) == "version")
    {
        Notify(id, "I am running OpenCollar version " + my_version, FALSE);


 dataserver(key id, string data)
    {
        if (id == my_version_request)
        {
            // we only ever read one notecard ("~version"), and it only ever has
            // one line.  So whatever we got back, that's our version.
            my_version = data;        

            // now request the version from github.
            CheckForUpdate();            
        }
    }
```

those snippets any useful? shall we do that?

**Comment by TucoSolo** [comment]
I would like to comment on the first note, about the version number in the main menu.
As a user, I would rather expect to find the version number in the Help menu. Compare with "About" in applications or web sites.
If put in the Help menu, the button Get Version can go.
