### ISSUE TITLE
OpenCollar 3.930 - Badwords: "ClearAll" don't work!  bug

### ISSUE THREAD

**Issue by ghost** [OpenCollar/opencollar#22]
98    list lButtons = ["List Words", "Clear All", "Say Penance"];
.....
.....
457                else if(sMessage == "Clear ALL") UserCommand(iAuth, "badwords clearall", kAv);

**Comment by WendyStarfall** [comment]
pushed the fix to main and beta, thanks a lot for reporting this!!
