### ISSUE TITLE
3.960 Build 38; OpenCollar - badwords.lsl

### ISSUE THREAD

**Issue by WendyStarfall** [OpenCollar/opencollar#220]
In 3243195cc004ba6f3b6c11c80279c69736da0c18 I added a Clear All button to the badwords root menu.

We need to verify that it clears all the badwords.
It needs a re-menu.

**Comment by ghost** [comment]
what do You mean?
clears all the badwords only 
or
clears all the badwords and reset penance, animation and sound to defaults ?

p.s. 'Clear All' already have in 'Remove Word' menu
