### ISSUE TITLE
REAL LEASH

### ISSUE THREAD

**Issue by Attitum** [OpenCollar/opencollar#227]
Expected Behavior is restrictions upon being leashed.
Expected restrictions >  list g_lRestrictionNames= ["fartouch","sittp","tplm","tplure","tploc"];

Experiment
1 Start with Basic Collar
2 Update the hell out of it :)
3 Click it :) 

goto [ Main Menu > Leash > Post ]
Post to a Grabby Post

*\* No restrictions being applied **

Expected Behavior = nice and restricted :)

**Comment by SilkieSabra** [comment]
Tested this one with my collar test alt--added an owner, was unleashed with strict leash enabled, on leash no restrictions were triggered.

**Comment by Attitum** [comment]
[ Main menu > RLV ]

Selecting OFF
Then ON
Does in fact produce a working real leash errrrrrrrr  Strict leash in working order :)

[12:52:35] OpenCollar: You unleash yourself from Grabby Post.
[12:52:39] OpenCollar: Strict leashing disabled.
[12:52:58] OpenCollar: Checking you out for hotness (and RLV), please wait a moment before use.
[12:53:11] OpenCollar: Strict leashing enabled.
[12:53:19] OpenCollar: You take your leash, and tie it to Grabby Post.

RestrainedLove viewer v2.7.0 (RLVa 1.4.8)

OpenCollar (Chest):
  -> tplure:50dfdefc-c775-f072-3090-8b586caf10b6
  -> fartouch
  -> sittp
  -> tplm
  -> tplure
  -> tploc

**Comment by SilkieSabra** [comment]
yes, solution is to toggle RLV off and on again in the collar rlv menu, this works!

**Comment by SilkieSabra** [comment]
and here is the update instructions--this may happen on an update that rlv doesn't get a complete handshake, in that case toggle rlv off in the collar menu:  http://www.opencollar.at/updates.html
