### ISSUE TITLE
Pose lock and Posture lock permissions

### ISSUE THREAD

**Issue by littlemousy** [OpenCollar/opencollar#228]
At 3.960 release, wearer could override owner's posture and pose lock settings.  This has been patched to allow only "better than wearer" access for both locking and unlocking both.  It needs expanding with a "Cannot override restriction placed by someone with higher auth", as is seen in other parts of the collar.  This "last auth level" will also have to be stored in settings to be properly persistent.

**Comment by JoyStipe** [comment]
Mouse, peek at leash.lsl, search/find "g_iLastRank" & follow how it is handled. Storage in settings should not be necessary, though I'll defer to animations experts on that one.
