### ISSUE TITLE
User_bell - Defaultsettings

### ISSUE THREAD

**Issue by Attitum** [OpenCollar/opencollar#232]
1 - Like always start with Basic collar
2 - Update it adding all your fav options only this time include bell :)
3 - wear + Mod your defaultsettings notecard + SAVE
4 - Take off the collar and put back on OR pass to alt

Observe the menu showing the bell is turn on but NOT ringing while you move
*\* if you havent turned on your speakers now would be a good time :-)

Expected result - when placing the following line in defaultsettings > 
                   User_bell=on~500~show~1~sound~0~vol~5~speed~10

Should be - Bell Rings, Collar menu shows bell is on however nothing rings.
Yes if you go in menu and turn bell OFF then back ON it will ring but this defeats having the bell option in defaultsetttings.

**Comment by littlemousy** [comment]
Well spotted xEmpiricalx, and thanks for the fix (#233) Romka

**Comment by Attitum** [comment]
INFO - Tested that code  from Romka

Using basic collar with only bell chosen for update.

Does not fix it - tested just now :(

on_rez(integer param)
{
    g_kWearer=llGetOwner();
    g_sSubPrefix=AutoPrefix();
    if (g_iBellOn) llRequestPermissions(g_kWearer,PERMISSION_TAKE_CONTROLS);

**Comment by littlemousy** [comment]
Think I got it.

Replaced bitwise & for logical && in test for getting permissions after new settings are received.  g_iBellOn is not a bool, it is an int reflecting auth level of last user to set the bell.

https://github.com/OpenCollar/OpenCollarUpdater/commit/85b80100bf51d71b8c8bd686cafb2027d8ee94f3

**Comment by ghost** [comment]
I think, need  'classic' llResetScript() on_rez
because all parameters are loaded

**Comment by littlemousy** [comment]
I don't see the need for a reset on rez, its just a bunch of extra work for the scripts to do on startup.
