### ISSUE TITLE
Remote Add Sec Owner by Chat Command

### ISSUE THREAD

**Issue by SilkieSabra** [OpenCollar/opencollar#236]
Adding an owner by chat command using <prefix>owner <UUID> is working great and needs to be extended to sec owners also--per convo with mousy inworld, "lines 572 and 573 need to be changed to be more like lines 536 to 544"

**Comment by littlemousy** [comment]
fixed, in https://github.com/OpenCollar/OpenCollarUpdater/commit/006a5aa2d8352c14e6ca7725ae271fea161684aa
