### ISSUE TITLE
@versionnew=123456 creates a duplicate reply

### ISSUE THREAD

**Issue by george-black** [OpenCollar/opencollar#238]
Bug report from OpenCollar R&D Group Chat:

[05:32] Toy (toy.wylie): Someone who is reading along and has a github account can file it of course. "@versionnew=123456 creates a duplicate reply".

**Comment by JoyStipe** [comment]
if that only happens with that one number, it sounds like an issue for rlv api. the function should work correctly using any positive integer, as detailed on this url:http://wiki.secondlife.com/wiki/RestrainedLifeAPI#Version_Checking

Come to think of it, check yourself for two relays. LOL if you require assistance with that let me know, I have a relay tester that tells me how many relays people are wearing

**Comment by SilkieSabra** [comment]
Ivanneth in world has duplicated this with a different channel number:
@versionnew=70251 also generates a duplicate reply--this needs more testing seems to me.

**Comment by JoyStipe** [comment]
it isn't just that command - verified this issue today (and to more extent)
while testing/debugging an iwo rlv script: gets double responses from relay
(OC built-in relay) to queries: @getoutfit, @getattach, & @getstatus.
Checked/verified only one active relay on at the time.

On Mon, May 19, 2014 at 2:56 PM, SilkieSabra notifications@github.comwrote:

> Ivanneth in world has duplicated this with a different channel number:
> @versionnew=70251 also generates a duplicate reply--this needs more
> testing seems to me.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/OpenCollar/OpenCollarUpdater/issues/238#issuecomment-43563582
> .

## 

~ A bug is a feature with seniority

**Comment by WendyStarfall** [comment]
happens in rlvmain; it's not breaking functionality thankfully so we can continue working on rlvmain more in-depth before having to release anything; shout-out to Satomi and mouse!

**Comment by littlemousy** [comment]
Thanks to Satomi for spotting the bug.  Its in the code that tries to refresh rlv restrictions after teleport.  Swap the >= for a < at line 755, seems to fix it.
