### ISSUE TITLE
3.960 menu issue: menu does not fix when scripts are removed

### ISSUE THREAD

**Issue by ghost** [OpenCollar/opencollar#241]
I have expressly left out certain scripts from my pet's OC 3.960. One such script is the Animations script.
When I look at the menu, the Animations option is still there. Going into Options -> Fix Menus does not remove it.

Please ensure your Main script removes scripts that are not present in the OC's inventory, as would be the expected behaviour since earlier versions.

(Closed because I thought this was in the wrong thing, reopened because it was not.)

**Comment by SilkieSabra** [comment]
The main menu is not designed to be a locus for modular elements either to add or subtract them, thus we can't write it to automatically remove or add buttons when you mod the collar.  However you can easily do this manually by removing the string "Animations", from the static buttons list in main, at line 137.

**Comment by ghost** [comment]
This is strange, because in earlier versions I was sure that the main menu did rebuild with removal/addition of scripts. Am I just mistaken or was this changed somewhere along the lines when I did not notice? (Could be, as I usually didn't take out that many scripts.)
It would be nice to see the main menu (re-)made to be more modular as well, considering the problems with things like the Animation system.

In this case, not being a bipedal avatar in SL, the choice was made to drop the Animation system, as well as some others.

**Comment by WendyStarfall** [comment]
Hi, don't worry, the animations system is correctly uninstalled if you unticked it for a custom update. The button stays around but animation specific scripts are removed and scalar animations are no longer increasing the content count in the collar.

In earlier versions the main menu used to arrange itself modular style like all the other menus. We would like to avoid situations where we end up with multi-page main menus, buttons jumping around all over the place, users getting confused after updates by slowly assembling or incomplete main menus in high latency regions.

Animations sticking around as a button is only a cosmetic concern at the moment. The main menu is faster, slimmer and more solid in summary. We can look into having the buttons removed if a "core" feature was uninstalled (RLV, Animations, Leash or whatever is each individuals opinion what counts as "core"..) and also make a decision if those three buttons, which we can now safely offer as free space, should become user customizable, i.e. have Grab there for the leash or #RLV Folders or Pose etc..

**Comment by ghost** [comment]
It's fairly easy to change the menu so that it checks to see if the scripts it is expecting to find are actually there. I could code a patch for it if you need one.

**Comment by SilkieSabra** [comment]
This was a design decision to protect the main menu from changes to its view, not an oversight , so thank you for the offer to write us a patch and may we call on you another time?  It is as i stated quite easy to remove the button in the script itself.

**Comment by ghost** [comment]
@SilkieSabra From a user's point of view it's an oversight. From a developer's point of view I can see how it's a design decision, but from a user's point of view it makes no sense.
Imagine JohnDoe Resident with 0% programming knowledge having to follow your suggestion and "remove the button in the script itself". Oops, they accidentally removed something else. Now their collar isn't working. What you're ending up with is a bunch of collars that don't function at all, with error messages all over the place.
I do hope you can agree that this is something that should be avoided.

Now there are reasons enough for the main menu to remain somewhat similar between versions, especially with the whole Owner HUD thing relying on certain functionality to be present. But you can't expect a total code noob to go in and edit the code just because they have a collar they don't need an Appearance version for, not needing the Animations menu, and so on.

As such, it's an oversight.

**Comment by JoyStipe** [comment]
@Makitk If they're that much of a noob, or hell even if they aren't and they just don't understand LSL at all - they have no freakin business trying to edit it to begin with. If they break it, lucky for them it's free they can get a new one. Anytime. Any day. Any week. Etc. If they break it again, they really should consider the wisdom in taking a car to the butcher to repair, or a cow to the mechanic to cut up, before breaking another. As provided, OpenCollar products will not intentionally harm themselves, nor any users, providing an exclusion for LL, as they are quite practiced at breaking things. You removed a script (if I followed correctly), and want for us to put a band-aid on your menu. If you can't figure it out, especially when help has been offered and provided, then you do not have business cutting the cow open, to begin with.

**Comment by ghost** [comment]
@JoyStipe: I have already stated I can easily create a patch for inclusion in a future update of OC to make a modular main menu, as a regression to an earlier state where the main menu WAS modular, since it is the behaviour I had come to expect. I am quite able to put a "band-aid" on the menu myself, but I am confused as to why there is such hostility towards the idea that the main menu could potentially contain elements which some users may wish to have removed and the idea that the main menu, as all menus, should optimize itself to the removal of these scripts, omitting the buttons which would otherwise lead to this functionality.
