### ISSUE TITLE
False update pop-up

### ISSUE THREAD

**Issue by kekemistwood** [OpenCollar/opencollar#242]
I went to put my collar on and I got a pop-up saying, "New Update Available."
So I got a new updater, rezzed it and went to the update menu. The new update is 3.950. It said I have version 3.950 in the update tab, but to be sure, I just updated it anyway. Once it was finished, I put it on and the pop-up for an update came back.
Please fix this issue, it's very annoying.

**Comment by littlemousy** [comment]
It's always worth asking for advice from in-world support before filing a bug report against the software.

3.950 is an old updater.  Get a new one from the Marketplace (https://marketplace.secondlife.com/p/OpenCollar-Updater/5493698), or from a vendor at the temple in-world (http://maps.secondlife.com/secondlife/Glint/26/105/47).

If you still have issues updating, either ask for help from one of the Open Collar helpers if there are any at the temple, or use the in-world support group, "OpenCollar Chatter".  You'll get help faster there than you will here.

Good luck with your update!
