### ISSUE TITLE
OpenAccess and unlimitted range together makes menus unavailable

### ISSUE THREAD

**Issue by OpenNC** [OpenCollar/opencollar#245]
This was reported in the OpenNC cuffs as a problem from Iori6150 . I have duplicated the problem in the cuffs and collar Auth code.

Test set-up with collar running 3.960 as -
No owners (not tested with owners as well)
Public access =yes
limit range = no
with this set you can still access menu system and list owners etc. and any other person has access to menu as expected.
close the dialog box
Menu system unavailable through touch or menu to anyone including wearer.
runaway works and is only option to gain access to collar again

Additional -
if set above and other AV trys a runaway command then wearer returns a debug message of "Invalid Key passed to instant message."

**Comment by OpenNC** [comment]
In OpenCollar - auth
section starting 297 - integer in_range(key kID) {
setting to public only and un-comment lines 302 and 307
chat command for menu by wearer returns- Classic Collar 3.960:  is not in range...
if another AV access the collar you get a double return -
Classic Collar 3.960: North Glenwalker In range...
Classic Collar 3.960:  is not in range...
if range set to unlimited range it always returns - is not in range and so will not return menu.

**Comment by OpenNC** [comment]
I have tried a pull request but my stupid setup won't let me!!!!
What happens is if access set to public and LimitRange set to no then any new menu open by another AV causes the Openaccess check to go into a loop from NO_AUTH with a NULL_KEY
Change to line 345 will fix this so it does not do an OpenAccess check if key is NULL- 

else if ((g_iOpenAccess)&& ((key)kID != NULL_KEY))

**Comment by WendyStarfall** [comment]
I will be home tonight, then I can try to reproduce it again but still couldn't. Are you sure this is without any plugins added or something in a custom owner hud?

**Comment by OpenNC** [comment]
This was in a stock collar, and guess what, I can not reprodue it again just now with a new collar, I will check with who reported it to me and see if they are still seeing it (but they do not have english and use google translate)

This was a very plain error, but now un repeatable.... close this now
