### ISSUE TITLE
OpenCollar 3.931 - Badwords: button "ClearAll" call DialogBadwords twice

### ISSUE THREAD

**Issue by ghost** [OpenCollar/opencollar#25]
when press button "ClearAll", DialogBadwords(kID, iNum) call twice, in line 363 (in UserCommand() function) and in line 475 ( in DIALOG_RESPONSE processing )

I think, in line 363  DialogBadwords(kID, iNum) is not needed

**Comment by WendyStarfall** [comment]
I'm gonna monkey with that when I'm done with the update for the AO; that means probably around sunday noon if I manage to push the AO update until saturday noon

**Comment by TucoSolo** [comment]
When I use the command 'badwords clearall', a dialog pops up, unexpectedly. It's the call from line 363. I also believe this line should go.
