### ISSUE TITLE
physLayer and TattoLayer not replaced when Smartstrip on

### ISSUE THREAD

**Issue by steampilot** [OpenCollar/opencollar#261]
expect to override  the physics layer when seting up folder as follows and using smartstrip
# rlv

|- bouncy(nostrip)
|  |- bouncy mesh  booby prim(chest)
|  |- bouncy physics layer
|- firm(nostrip)
|  |- firm dumy invisible prim(chest)
|  |- firm physics layer

execute chat command:
sub+firm
(attaches the invisible prim and the firm physics layer)

sub+boucy
(replaces the inv prim with the bounzy boobys  and ADDS the physics layer)

sub+firm
(replaces the boobys with the dumy prim and ADD the allready addet Physicslayer)

the effect is a flat sunken chest wit hyper jiglynes 

not using Smartstrip results int perfect function but then again . no protection for huds and attachments when stripped

i like to have more controll on what i want to get stripped and what not ... i am used to teach my subs that they HAVE to put Skin HAir Shape TAttoo Physics HUds into a (nostrip) folder

same problem wit the physich i have also with the tatoos

might this code fragment be the case?
 if(g_iSmartStrip==TRUE)
            {
                integer x=14; //let's not strip tattoos and physics layers;
                while(x)
                {
                    if(x==13) x=9; //skip hair,skin,shape,eyes
                    --x;
                    string sItem=llToLower(llList2String(DETACH_CLOTH_POINTS,x));
                    llMessageLinked(LINK_SET, RLV_CMD, "detachallthis:"+ sItem +"=force",NULL_KEY);

```
             }
        }
```

**Comment by SilkieSabra** [comment]
i am not sure what your actual issue is, because you don't say what particular result is something you don't want--but the (nostrip) tag only works if you name the actual item that, or the folder it is in immediately, it does not work if you name a top folder (nostrip) and then insert subfolders not named (nostrip)--see the very last sentence on this page: http://www.opencollar.at/folders.html
