### ISSUE TITLE
Medea Destiny's AO Link

### ISSUE THREAD

**Issue by WendyStarfall** [OpenCollar/opencollar#263]
> ##### Medea Destiny's AO interface script for OpenCollar
> 
> This script is inteneded to be a drop-in for ZHAO-2 and Oracul AOs that
> are not already compatible with OpenCollar's AO interface.
> 
> Scope: The script tries to identify the AO type by checking script
> naming. It receives the ZHAO ON, ZHAO OFF and ZHAO Menu commands from
> the collar, and uses link messages to send appropriate commands to the
> AO, depending on the detected collar type. It is not a complete
> replacement of the Sub AO as it cannot allow as complete access to the
> AO as that does, but it should provide most of the functionality while
> being very easy to add to user's pre-existing AOs.
> 
> When the AO is switched on, but the collar sends a command to switch it
> off, the script will take controls and detect for movement. While the
> avatar is trying to move, the AO will told to switch the AO back on
> again until movement ceases.
> 
> An alternative to this method would be to capture the AO's walk
> animation and play the animation itself as a walk overrider. The
> disadvantage of that is trying to capture the walk animation isn't
> straightforward, particular when there is more than one walk configured.
> The disadvantage of this method is that it does a lot more AO
> triggering.

:heavy_exclamation_mark: 1e9a2b5f28d05275c541db0bb7325c1ea7026d49

Quoted above you see Medea's initial notes.

This concept works and I could successfuly use it for Oracul and older ZHAOII overriders. I think we should polish this script up neatly and maybe consider making it two variations; dedicated Oracul and dedicated ZHAOII. No success was reported when dropping this into recent Vista AOs. I cannot test this myself because I'm not willing to lay down the cash for a recent Vista AO, I'm sure some of you might own one however and could run a couple tests.

I believe that the times when users would customize an AO from scratch with individual animations are over. It is easier to explain a user how they drop 1 script into their existing AO than moving hundreds of animations and composing new AO set cards.

Please share your opinion and ideas and let's make this a proper full release!

**Comment by XenHat** [comment]
I am not exactly sure how recent my most recently purchased VISTA AO is, but it uses the new Vista square-ish hud that collapses onto itself:
![image](https://cloud.githubusercontent.com/assets/980408/3436529/121b1382-00a2-11e4-9ade-eb8d582c6909.png)

But here's what mine says:

> [17:12] VISTA ANIMATIONS _HUD3.9e_ THE MOST WANTED AO V1.2 (SHORTAVI): Cannot identify AO type. The script:OpenCollar - AO Link 0.100 is intended to be dropped into a Zhao2 or Oracul AO hud.

It would appear that VISTA ao's are still ZHAO-based...
![image](https://cloud.githubusercontent.com/assets/980408/3437898/72f72de0-00ba-11e4-988a-22714e67d977.png)

However the scripts are nomod:
![image](https://cloud.githubusercontent.com/assets/980408/3437917/d87a771c-00ba-11e4-8f11-0ceb8c3bee8b.png)

**Comment by XenHat** [comment]
Basic VISTA AO Support has been merged in. What next?

**Comment by WendyStarfall** [comment]
#264 
Thanks! :mushroom:

**Comment by XenHat** [comment]
My pleasure :smile_cat:

**Comment by AlistairBrownlee** [comment]
Also not compatible with Akeyo yet. HUD reports: "AKEYO_PowerAO_AlphaMale_HUD: Cannot identify AO type. The script:OpenCollar - AO Link (lite) is intended to be dropped into a Zhao2 or Oracul AO hud."
