### ISSUE TITLE
OpenCollar - label.lsl  possinble bug?

### ISSUE THREAD

**Issue by ghost** [OpenCollar/opencollar#266]
I think that the 'g_iCharLimit' is calculated incorrectly 

247:         if (iCharPosition > g_iCharLimit) g_iCharLimit = iCharPosition;

where, if the 'iCharPosition' starts with 0, and with 12 label prims ends with 11,
then the 'g_iCharLimit'  is 11, not 12!

I put "llOwnerSay ((string) g_iCharLimit);" after "SetLabel ();" at 424 line and he said "11" when my collar has 12 label prims...

**Comment by WendyStarfall** [comment]
We need the -1 at the integer for the trick to be able removing label scripts if not label prims are present at line 426

Maybe we could start label prims at 01 instead of 00?

**Comment by ghost** [comment]
many collar designers make label prims starting with 00 ,
and iCharPosition gets from prim description, and must begin with 0 for llGetSubString(sText, iCharPosition, iCharPosition)

**Comment by WendyStarfall** [comment]
Is there any other issue with this apart from the text being off-center in labels with 12 prims?

**Comment by ghost** [comment]
no more problems :)

**Comment by WendyStarfall** [comment]
Are you not going to send a pull for your label with the scrolling text? :disappointed:

**Comment by ghost** [comment]
Only if necessary

**Comment by WendyStarfall** [comment]
We just need to make sure that the label script cleans itself up if it is installed in collars without label elements.

**Comment by ghost** [comment]
I'll check it

I'm still not sure that scrolling works well and smoothly

**Comment by WendyStarfall** [comment]
I think smoothness will depend a lot on sim performance as well. Please go ahead and send us the pull, we can also push the scrolling label to SPARE PARTS if you feel insecure yet that it is good enough to go?

**Comment by WendyStarfall** [comment]
Hi, I pushed the source for label to SPARE PARTS, referring to #271 

You can edit the script there and send the pull request one more time, please?
https://github.com/OpenCollar/OpenCollarUpdater/blob/main/SPARE_PARTS/OpenCollar%20-%20label.lsl

**Comment by ghost** [comment]
I've done

**Comment by WendyStarfall** [comment]
#272 pulled! Yay! :smirk_cat:
