### ISSUE TITLE
Reset All in Owners menu pops up unusable Owners menu

### ISSUE THREAD

**Issue by TucoSolo** [OpenCollar/opencollar#27]
**What is your Second Life name?**
Tuco Solo

**What steps will reproduce the problem?**
As a sub, click Owners -> Reset All (whether you have owners or not)

**What is the expected output?**
A dialog that can be used, or no dialog at all.

**What do you see instead?**
A dialog that can not be used and a runaway message (the latter is fine).

**What version of the collar (or other item) are you using?**
3.931

**Please provide any additional information below.**
The messages read:
[14:19:40] OpenCollar - 3.931: Running away from all owners started, your owners will now be notified!
[14:19:40] OpenCollar - 3.931: Runaway finished, the collar will now release locks!
[14:19:40] OpenCollar - 3.931: You unleash yourself from .
[14:19:40] OpenCollar - 3.931: Unlocked.

This is a copy of issue #1515 at code.google.com, which reports this would have been fixed in version 3.800. Changing (internally) from reset to runaway may have changed insights that may have caused this issue to reappear.

The runaway-command seems to be processed in the auth script, from line 840 and further. At the end of the block, the script resets, so there's no way this script can react on any dialog response. (However, at this point it's not clear to me what script causes the new dialog.)

**Comment by TucoSolo** [comment]
Note:
Trying to tackle this issue just by reading the code, I noticed something that may need some further attention. In the link_message event, there's first a check for (iNum == COMMAND_NOAUTH). Within that true-block, there's checks for (iNum == COMMAND_OWNER || ...).
This check for COMMAND_OWNER is obsolete. In fact, if you're scrolling down the code and you miss the first if-clause, things may get confusing. I would recommend for this to be straightened out.

**Comment by KaroWeirsider** [comment]
The simple fix since this resets the script anyway would be to prevent the menu from being re-displayed. This would be done in OpenCollar - auth by adding a line immediately following line 1087 and adding a return;
The following starts at line 1085:
 else if (sMessage == g_sReset)
                   { // separate routine
                        llMessageLinked(LINK_SET, COMMAND_NOAUTH, "runaway", kAv);
                    }
would become:
 else if (sMessage == g_sReset)
                    { // separate routine
                        llMessageLinked(LINK_SET, COMMAND_NOAUTH, "runaway", kAv);
                        return;
                    }

I would further this by adding a confirmation to the runaway routine. Currently one click and you runaway. Those changes would be for another thread being this one deals only with the non-reactive dialog.

**Comment by WendyStarfall** [comment]
thanks, Karo!

we should think about confirmations for 4.0.0 where everything will be made from scratch; I thought about a safety check myself once and then wondered why would anyone Reset All or <fix>runaway if they wouldn't want to though?
