### ISSUE TITLE
Grabby Post can't leash

### ISSUE THREAD

**Issue by TucoSolo** [OpenCollar/opencollar#28]
**What is your Second Life name?**
Tuco Solo

**What steps will reproduce the problem?**
Rez the 'Grabby Post' that is sent to your inventory by the button "give Post" in the Leash menu. (Or just hit Rez Post in the same menu.)
Touch it. Select Scan in the dialog menu.

**What is the expected output?**
A list in the dialog of found avies nearby.

**What do you see instead?**
No avies listed.

**What version of the collar (or other item) are you using?**
3.931

**Please provide any additional information below.**
- The version of 3.2 in the script's name suggests this script hasn't been updated in recent versions.
- A ping is sent (in MassPing(), verified), but I haven't been able to find the collar script that should respond to this ping. If this feature was deliberately removed, I think this script in the post should be removed.
- The script uses variable LISTEN as a boolean (TRUE/FALSE) and as an integer (listen handle). As long as the listener this integer records is always the **first** listener activated, it will work. In other words, current algorithm protects this unorthodoxed use of the variable. I would advise to straighten this out (if the script is kept, see above).

**Comment by WendyStarfall** [comment]
Fixed it. The culprit was a wrong prefix at line 121:

``` C#
list data = llParseString2List(m, [":"], []);
```
