### ISSUE TITLE
Do we really want an Options menu?

### ISSUE THREAD

**Issue by WendyStarfall** [OpenCollar/opencollar#283]
If we could instead nest something more useful in the Main Menu, like Un/dress and move options into Help/About?

The only actual option in Options would be [] Personal where we give User_ priority over collarid_

**Comment by XenHat** [comment]
Since I always tend to look in Help for stuff like "Update" and what not... Sure, why not?

**Comment by WendyStarfall** [comment]
I will close this because Options could be used for more useful things. Personally, I don't think settings should create this menu but main should and receive "options" from several other scripts.
