### ISSUE TITLE
Blacklist option in timer?

### ISSUE THREAD

**Issue by masterofsorts** [OpenCollar/opencollar#284]
Can we add an option that a wearer who owns there own collar can set a blacklist timer, such that they can add a secondary owner to their collar, then blacklist themselves from the collar for a period of time? This might solve the temporary ownership thing for while?

**Comment by WendyStarfall** [comment]
A plugin/app/attachment will be able to do this hopefully for 4.0

The timer we currently have will be replaced with a service -> #311
