### ISSUE TITLE
The relay should also smartly strip!

### ISSUE THREAD

**Issue by SatomiAhn** [OpenCollar/opencollar#293]
Smart strip is nice to have as a general rule (as long as underlying avatar appearance tech and RLV API stay as they are).

I want to remark however that it is only nice insofar that legacy scripts will still use @remoutfit:xxx=force.
While it makes (legacy) rlvundress useful again (but in my opinion, there would be surperior solutions using rlvfolders), the only place where smart strip really is vital is in the relay, as we indeed have no control over the scripting of third party traps.

What I want: to add smart strip capacity to the OpenCollar relay.

How I believe it should be done: move smart strip support deeper in the backend (i.e. in rlvmain script), thus translating every @remoutfit command into @detachthis commands, no matter their origin (rlvrelay, rlvundress, other legacy plugin). The toggle button could stay where it is but would be better situated under RLV menu (or RLV/Options... ).

Where this might go wrong: if some plugin really wants @remoutfit for some reason (likely dubious reasons, I am afraid... or am I wrong?)

I think I can script this quite easily, but I wanted to make sure this makes sense to everybody.

**Comment by SilkieSabra** [comment]
This makes tons of sense to me, i'm sorry i took so long to respond, but it's a no-brainer, YES!! that is, if it doesn't require the user to get their head around yet another new and different way to organize their folders or use the collar menu.  If it does, i would want to see the difference--not being a scripter i have a weak grasp of what @remoutfit does vs. @detachthis

**Comment by littlemousy** [comment]
I can't think of any negative implications from this.  I say go for it.

**Comment by SatomiAhn** [comment]
Ok, as soon as I can get some available time I do this :). Unless somebody feels like doing it before then.

**Comment by WendyStarfall** [comment]
Didn't happen in almost a year and internal relay plugin as well as un/dress with smartstrip are optional for 4.0 if somebody makes un/dress and relay work properly for the new API at all; not volunteering - _ -
