### ISSUE TITLE
leash access restriction

### ISSUE THREAD

**Issue by JoyStipe** [OpenCollar/opencollar#298]
Suggestion: an access to leashing privileges - an owner-only settable option to allow/restrict wearer or sec-owners (etc) to even leash a collar wearer, whether to themselves, another, or an object. The thought process is for owner to be able to prevent allowing a sub to leash themselves to anything/one, as a setting.
Alternatively, this could also just be a hard setting - that allows only primary owners to use the leash of a collar.

**Comment by SilkieSabra** [comment]
I tentatively like the idea of locking out the wearer from the leash, maybe as part of the Strict Leash setting, but i totally hate the idea that sec owners or public access would also be locked out of the leash--for that you might as well just not have public access or sec owners--they are already unable to unleash from a primary owner.

**Comment by XenHat** [comment]
I personally dislike any change in behavior concerning the leash
permissions. I'm not against a finer control over what/who can be leashed
to/can do the leashing(sic), but I would rather put that with an "access
list" plugin in the 4.0 development pipeline. I am strongly against any
hard-coded change to prevent the wearer to put the leash where they want to
without an option to allow it.

**Comment by WendyStarfall** [comment]
superseded by #341
