### ISSUE TITLE
auth 3.967; runaway logic no longer requests loadcard

### ISSUE THREAD

**Issue by WendyStarfall** [OpenCollar/opencollar#300]
Hardwired settings must be requested from card after a Reset All in the menu or if a runaway chat command is performed. Current collar version at 3.971 is missing this request for some reason.

We cannot release an auth based on 3.968 yet, so let's hack it for 3.967 and do it properly for the refactored auth past 3.968. That means we only work in-world and don't push the hacked 3.967 here.

**Comment by WendyStarfall** [comment]
Thanks a lot to Sumi Perl for helping with this fix. A patch release 3.972 will ship during the weekend.

**Comment by WendyStarfall** [comment]
Looks like this has to be discussed a lot more than I imagined when we hacked it real quick earlier.

Opinions how this case should be handled differ greatly:
1. The card is intended to _backup_ settings.
2. The card is intended to _hardwire_ settings.

Where the 2nd case here means that locks, restrictions and owners are indeed permanent to an extent that unlocking and running away is disabled **forever**.

Until a mutually acceptable agreement could be found, I cannot release this modification as a patch for OpenCollar.

This is going to be a key decision. :confused:

**Comment by masterofsorts** [comment]
Surely we can enabled both scenarios
Howabout a global variable in the notecard that when the notecard is loaded for the first time it prompts the user if they want to accept permanent settings. Then once this variable is set can be used to run an alternate reset function that reloads the notecard  and does not show a prompt for acceptance

**Comment by WendyStarfall** [comment]
The change here would have been for the current 3.9 versions where backup storage turned to hardwiring and hardwiring turned to backup storage probably sometime along the way.

I'm going to close this issue. It's being addressed with #308 thankfully
