### ISSUE TITLE
Static poses are kept while moving

### ISSUE THREAD

**Issue by Bondmaster** [OpenCollar/opencollar#305]
The static poses set trough the Anim menu are by definition "static".
These might look very odd when a sub need to move, as the effect is to "slide" around while immobile.
I'm submitting a change via pull request that stop the animation (trough the animation standard ease-out, so not always immediate) and set the pose back as soon as the sub stop moving.
It use a timer to check the current AVI movement status, but only if a pose is actually set, so it should not introduce a relevant lag. Also tests didn't show any drawback so far.

**Comment by WendyStarfall** [comment]
There are currently two solutions provided for that:
1. The Sub AO itself
2. The AO Link drop and go script (found in SPARE PARTS)

A partly implemented solution we have in Firestorm internal AOs that makes use of the LSL bridge to simply turn the whole AO off. This could be improved by deactivating to override stands only.

**Comment by Bondmaster** [comment]
I understand the solution you reference works the other way around, stopping the current AO when a pose is set or a collar anim is playing, but don't allow them to temporarily kick back if the anim is moving while the pose is still active and then get the static pose again when the avi stops.

**Comment by SilkieSabra** [comment]
i've often wondered about this because some of the poses stop when the sub walks and others don't, cutie for instance reliably cedes to the walking animation

**Comment by WendyStarfall** [comment]
handled with #364 for the 3.980 branch

We will see if to make selectable walks to avoid duckwalking but so far this works well.
