### ISSUE TITLE
settings; fix menus polish

### ISSUE THREAD

**Issue by WendyStarfall** [OpenCollar/opencollar#306]
After clicking Fix Menus, we no longer get an annoying Options re-menu. \o/

That is good but we drop out of the menu fully if clicking the OK button.

When we click OK in the prompt. "Rebuilding menus. This may take several seconds."
we should arrive back at the Main Menu for convenience.

**Comment by ghost** [comment]
may not use reset script?
just send 'refresh_menu' command to main menu script,
and in main script, use rebuild menu function, instead of resetting  main script?
it will be faster than reset script

in fact, there is no need to reset main script to update menu.

**Comment by WendyStarfall** [comment]
What I meant is that we need to arrive back at the Main Menu after clicking Ok in the FixMenus dialog.

**Comment by ghost** [comment]
another way 'Fix menu' #314 #315 

p.s. I think, need to change dialog script for ability do 'one button'

**Comment by WendyStarfall** [comment]
#312
