### ISSUE TITLE
Get Version button in Help/About does not show correct version right after update.

### ISSUE THREAD

**Issue by ghost** [OpenCollar/opencollar#32]
Right after update (collar is still on the ground), the version reported by the Get Version button in Help/About reports the previous version. This clears up after the update script is reset, so I think it must be that the update script begins to run or is already running before the ~version notecard is updated, and the script doesn't reset to account for the changed notecard.

Just a minor thing, really.

**Comment by WendyStarfall** [comment]
asset lag; it will either gobble the ~version card as updated or not if you query for it right after the update.

however if you pick up the collar after the update and query for it, it will report the correct version. same it would report the correct version if you did a worn update and re-attach the collar.

that's not our kink, it's the lab's and I honestly rather keep things the way they are than corrupting our update process by accident. I will see to document this better soon.
