### ISSUE TITLE
OPENCOLLAR RLVMAIN

### ISSUE THREAD

**Issue by NorthGlenwalker** [OpenCollar/opencollar#33]
Found while converting Collar scripts into cuff scripts.
Using 3.931 code
I would expect access to rlv menu to turn RLV on or off (in the cuffs we only use RLVMAIN)
instead I get -
Still querying for viewer version.  Please try again in a minute.

comments -
the code says it sould work as so -
//on script start, query db for rlvon setting
//on rlvon response, if rlvon=0 then just switch to checked state.  if rlvon=1 or rlvon=unset then open listener, do @versionnum, start 30 second timer
//on listen, we got version, so stop timer, close listen, turn on rlv flag, and switch to checked state

It is hanging waiting for a responce from the DB_RESPONCE on the link channel 2001.
In the collar I can see a rlvon responce on 2001, which I think is coming from the settings script... but in the cuffs the settings script (unmodified collar settings script) does not send this command even with adding it to defalt notecard.
I guess the settings script is waiting for a responce from another script first (one I have not converted to 3.931)
I have got around this problem for now
by adding -

if (g_iRLVOn)
        {
            CheckVersion(FALSE);//NG hack to force it to check RLV
        }

into the default, static_entry section

not sure if this is a bug or it is susposed to work this way

**Comment by WendyStarfall** [comment]
If you just ran an installation and didn't re-wear/re-rez the collar or pick it up and then wear it, you will need to flip RLV off and on for all scripts to understand "we are running RLV here". This procedure is only necessary if you did changes on one of the rlv scripts or if you did a fresh installation and had bad luck with the initial query. That means you only ever need to do this one, single time unless you tinker or cold boot.

**Comment by NorthGlenwalker** [comment]
No this was not an instalation it was a script copy from a undated collar, into the cuffs
The problem I have come across is I can not even get to the RLV menu to turn it on/off.
Once I have forced it to do a RLV check once, it then works everytime until I reset the script.

I don't know if the RLVMAIN script should be waiting for a rlvon message from the DB anymore since we no longer have one, it should do a default action if no responce from the DB with a time frame. At the Moment it just sits dead waiting for the DB to talk to it.
But as I said above, something in the collar is sending a rlvon messaage, acting like the DB

**Comment by WendyStarfall** [comment]
Try, without your hack, to add rlvex, rlvtalk, rlvtp and rlvsit. that's the "RLVMain" bundle. What is acting like the DB is likely settings because settings are what httpdb was.

All this is working fine in the collar though. I said it before: the cuffs are going to cause friction, they always did and they will again until we de-fuse them to act as cosmetic addition + lockmeister/-guard props for using them with furniture. I can already tell you that this would take a lot of time to figure out, that it would mean messing with rlv scripts, with auth, with settings and probably with every other script -> in the collar.
