### ISSUE TITLE
Update 3.971 generating script errors and RLV malfunction

### ISSUE THREAD

**Issue by ghost** [OpenCollar/opencollar#332]
Hi,
I recently did the update to 3.970 on my leather collar (OC default one) and it worked fine.
When 3.971 came out, after updating, the collar gave me script errors.
Since i was wearing the collar when doing that last one, i bought a new leather collar fresh from market place and did the update on the ground. same issue.

I bought another collar using an older version of the script (**RE** MaluS Choker Drako RLV). it uses 3.960.

I did the update to 3.971 on the ground and copied my defaultsettings notecard to it (generated with dump cache).

As soon as i remove myself from the owners list i get this :

**RE** MaluS Choker Drako RLV - Male 3.971 [script:OpenCollar - rlvmain] Script run-time error
Stack-Heap Collision

my restriction is disabled sendIM, with 5 exceptions. once the error pops in, i can't IM the person i was talking to, despite being in the exceptions list.

i disabled RLV in firestorm and restarted to do a RLV off/on, and when relogging with RLV off, the error pops up.
when back with RLV ON, same thing.

Now the collar menu is missing the RLV button. 'Fix menus' doesnt work. restrictions doesnt work. collar lock doesnt work. in Firestorm RLVa restrictions window, both restrictions and exceptions tabs are empty.

Does that ring any bell?
it IS extremely annoying ^^

**Comment by WendyStarfall** [comment]
Hi, I've created a defaultsettings variant with multiple owners, settings and 5 exceptions on 5 others.

Dumped the cache, got a fresh Leather Collar, updated it to 3.971, pasted the settings dump, picked it up and wore it. Then I have removed myself as owner.

I'm unable to reproduce the error. A copy of your settings paste could maybe give better insight. Names and UUIDs don't matter in this case and can be blotted out as long as we know amount of entries.

Possible causes:
- Speciality plugins with API versions below 3.7 had been added to the collar.
- A bad paste after the cache dump was copied.
- An out of date cache dump from versions below 3.841
- 3rd party modifications or additions to the software we are unaware of.

We are not affiliated with or supported by RE, please contact them directly for issues with one of their necklaces.

**Comment by ghost** [comment]
Hello Wendy!

a few answers : 
-i use no plugins at all
-i got the exact same error on RE and OC collars (they use the OC script without modifications as far as i know, but it doesnt matter, as i first got this issue with my OC leather collar.

Here's an "anonymous" copy of my config : 

#---My Settings---#
User_lock=locksound~794fd47e-90c7-87d5-4751-143c02e58148~unlocksound~e7403875-96d3-0213-c5a0-73e4d609e749
User_rlvmain=on~1
User_auth=owner~uuid1,owner1 name,uuid2,owner2 name,uuid3,owner3 name,ae4d520d-7be7-4ce4-8da6-e3b83d5c521f,Usopp Barbosa~secowners~
User_bell=on~0~show~1~sound~0~vol~5~speed~10
User_rlvex=List~UUID1,111,UUID2,111,UUID3,111,UUID4,111,UUID5,127

**Comment by WendyStarfall** [comment]
I've went over it again, then also adding the empty string for secowners~, 10 owners and 10 exceptions to try straining the memory but to no avail. Then I've deliberately created corrupted settings entries.

I've been unable to crash the rlvmain script.

Let's add more information to this query:
- What viewer are you using? (Brand/Version/Bit)
- Where were you at the time the script crashed? (SLURL)
- When did the crash exactly happen? (On Wear/On Teleport/On Lock/On settings paste/etc..)
- Are there any traps, cages or devices nearby that query your relay?
- Are you wearing/rezzing more than 1 item with OpenCollar scripts installed?

**Comment by ghost** [comment]
here's the info :
Firestorm 4.6.5 (40833) May  5 2014 06:27:24 (Firestorm-Releasex64) with OpenSimulator support

This happens at home http://maps.secondlife.com/secondlife/Asia%20House/21/15/23 but also anywhere else afaik

It happened just after i removed myself from the owners list to lock it properly, using the collar menu.
There are no traps or devices nearby interacting with the collar
I am only wearing one item with OC scripts.

**Comment by WendyStarfall** [comment]
Thanks for all the info!

We met on site and have been able to reproduce it by synchronizing the exact steps.

**Comment by WendyStarfall** [comment]
Mouse cooked up a fix for your case. I put it in an updater and sent it to you in-world.

**Comment by ghost** [comment]
I had no issues so far with the update!
It looks fixed to me. Maybe i'll wait to have my Miss play a bit with the settings, to see if it's all good.
I'll post again ASAP when we test the collar a bit more :)

**Comment by ghost** [comment]
So far, the collar worked flawlessly. I am OK to close this issue if it's OK with you.

Thanks again
