### ISSUE TITLE
Leash Guideline

### ISSUE THREAD

**Issue by WendyStarfall** [OpenCollar/opencollar#341]
#### Guideline:
- make OpenCollar - leashParticle.lsl only create particles
- rename this to OpenCollar - particle.lsl to distinguish clearly
  - refactor this to be the tiny program that will take care of every leash point on any core or extra
- move particle controller to a dedicated plugin
  - creators can use this to adjust leash textures and print values for ~paint configuration cards
- make ~paint notecard able to supply colours for the leash texture
- add two new default ribbon particle leashes
  - add leash particle texture type Band
  - add leash particle texture type Wire
    - both of these make use the default Blank texture to avoid "runny and stretchy" issue
    - add tasteful default colours for especially the Band in stock ~paint cards
- add confirmation dialog if wearer leashes themselves to others
  - "Wearer would like to pass you their leash."
  - "Do you accept/reject/pass-on?"
  - Passing it on triggers sensor dialog of nearby agents
    - This needs to be investigated for cases where wearer leashes themselves to others while group authorization is disabled
- analyse if strict leashing should be definable in ~restrictions configuration cards
#### Optimize:
- remove unused LM definitions
- in-line any functions only used once
- in-line any single-line functions
- refactor any inefficient use of multiple states

**Affected scripts:** _OpenCollar - leash.lsl and OpenCollar - leashParticle.lsl_
**Created scripts:** _OpenCollar - particle.lsl_
**Specialist assigned:** _none_

Please inform the assigned specialist if you wish to collaborate on this guideline. If no specialist is yet assigned, the guideline is up for grabs. Work In Progress labels mean we cannot accept pull requests for the scripts affected. Guidelines will receive appropriate labels to indicate when work has been completed.

**NOTE:** Remember to mention the issue number in your pull request title or description so it will be auto attached here. It's no big deal if you forget but would be extremely useful for others to keep up. Thanks!

**Comment by JoyStipe** [comment]
Whomever decides to take this project on, please coordinate with me to assist with a smoother transition from defaultsettings handles to separate notecard handles. I also developed synchronous particle streams for multiple attachments handled by leashParticle, quite some time back (will require adapting to newer particle script syntax).

**Comment by WendyStarfall** [comment]
This goal was partially and/or differently completed. Please check the oc_leash.lsl and oc_particle.lsl logs for detailed changes. The results are really decent. Shout out to @GarvinTwine here
