### ISSUE TITLE
option to allow wearers to unleash themselves

### ISSUE THREAD

**Issue by NorthGlenwalker** [OpenCollar/opencollar#342]
I have been asked if we can add an option where an owner can click a button to allow/disallow a wearer to be able to unleash themselves if the owner is not present.
This could stop the problem of a sub from being dragged 90M face first into a wall as their owner logs in.
or any other ideas?

**Comment by katijaAdored** [comment]
i would love to see collar wearers, ,by default, be able to unleash themselves, but to have an actual restriction that allows the owner at any time, to turn off that ability, for as long as they wish. it makes it simple by default, yet leaves the owners in total control. they can use the restriction sometimes or leave it on, like any other restriction. (i.e., if an owner wants a sub to have to stay leashed to a post and be unable to unleash herself, they could set the restriction then turn it back off; or, if they never want them to unleash themselves, they can just leave the restriction on.)

**Comment by NorthGlenwalker** [comment]
also what about an auto unleash if the wearer stops moving towards the owner, IE gets jammed in a wall, so if movement is halted when greater to lenght of leash for more then 5 seconds?

**Comment by ghost** [comment]
instead of an auto-unleash, an auto-TP to the dom's position would work better i believe. No need for the owner to re-leash the sub. its totally transparent and hassle free for both, as there's no need to stop, click the collar, and leash again.

**Comment by katijaAdored** [comment]
i'd like to add another reason it'd be great to be able to unleash by default is that some collars are sold copy/no mod, so you can't go into the leash script to make it so you can unleash. i seriously think allowing for NOT being able to unleash yourself as a restriction and to BE able to by default solves several problems from so many different angles and simplifies everything in several ways.

**Comment by ghost** [comment]
There's also a psychological edge that comes with that option :)
THe dom seeing his/her subbie staying leashed when he/she can detach it anytime feels pretty good :)
Finally, taking more situations into account, i find it a pretty good idea.

**Comment by ml132** [comment]
A problem with the "auto-tp" idea, is that many sims don't allow you to teleport except to the landing zone. On these sims, any teleport commands will just send the sub to the landing zone, resulting in an infinite loop of teleports...

One method that I think would work well, is to disable the leashing if the leash target is ever more than let's say 10m over the leash distance, but only temporarily. The leashing can be automatically reinstated when the sub becomes close to the leash target again.

**Comment by WendyStarfall** [comment]
closes with #345
