### ISSUE TITLE
Add RLV restriction/exception for Group chat

### ISSUE THREAD

**Issue by ghost** [OpenCollar/opencollar#343]
Hi,
Would it be possible to add an option to allow a sub to participate in group chat, even if he/she is IM restricted?

I don't know if group UUID is treated like avatars UUID, and anyway these can't be added through the menu of the collar since the group is not..."nearby"..

Thanks!

**Comment by WendyStarfall** [comment]
As far as I know, viewers disable group chat by temporarily adding the group ID to the block list.

I don't think we can do this with RLV at the moment but someone else might have greater knowledge.

**Comment by XenHat** [comment]
_Disclaimer: I don't pretend to be an expert on RLVa code (in fact I barely know how it works) , but having the code under my eyes most of my time, I would be happy to provide some help if I can._

The RLVa code (in firestorm, at least) doesn't appear to allow exceptions to _canReceiveIM_
However, it might be possible to request a feature to allow mute override.

As wendy said, RLVa does play with said Mute List, but apparently not in the way we would want to.
A patch could be done, if Kitty or someone else would spare some time for it, but it'd take a while to be integrated in a public release (we're talking months here).

for reference:

``` C++
//Firestorm // llimview.cpp
// re-formated to fit github box size

//don't return if user is muted b/c proper way to ignore a muted user who
//initiated an adhoc/group conference is to create then leave the session (see STORM-1731)
    if (is_do_not_disturb)
    {
        return;
    }
// [RLVa:KB] - Checked: 2010-11-30 (RLVa-1.3.0)
    if ( (RlvActions::hasBehaviour(RLV_BHVR_RECVIM))
        || (RlvActions::hasBehaviour(RLV_BHVR_RECVIMFROM)) )
    {
        // Group chat: don't accept the invite if not an exception
        if (gAgent.isInGroup(session_id))
        {
            if (!RlvActions::canReceiveIM(session_id))
                return;
        }
        // Conference chat: don't block; censor if not an exception
        else if (!RlvActions::canReceiveIM(from_id))
        {
        message = RlvStrings::getString(RLV_STRING_BLOCKED_RECVIM);
        }
    }
// [/RLVa:KB]
```
