### ISSUE TITLE
Badwords-addon only using first badword from defaultsettings NC; help/debug-settings-dump not correct

### ISSUE THREAD

**Issue by RayZopf** [OpenCollar/opencollar#38]
## How to reproduce
- Set up badwords addon with more than one badword (different effects when you use odd or even numbers of badwords!)
- make a dump of the settings and put them into _defaultsettings_ NC.
  - this is the line I use (dump, with 3 badwords)
    `User_badwords=badwordson~true~badwords~test-badword~testword2~testword3~penance~tis 's the testpenance!`
- Now reset scripts.
- you may check badwords and penance from within the badwords-addons menu
## Debugging

Starting here, https://github.com/OpenCollar/OpenCollarUpdater/blob/main/LSL/OpenCollar%20-%20badwords.lsl#L395
The addon now gets the settings like this (to see add):
`//DEBUG
llOwnerSay("link_message string: " + (string)sStr);`

and you will see the following (snippet)
_with 3 badwords:_

> link_message string: badwords_badwordson=true
> [08:54:30] OpenCollar-3.932-full: link_message string: badwords_badwords=test-badword
> [08:54:30] OpenCollar-3.932-full: link_message string: badwords_testword2=testword3
> [08:54:30] OpenCollar-3.932-full: link_message string: badwords_penance=tis 's the testpenance!

gives one badword (first one) and a working penance

_even worse with 2 badwords:_

> link_message string: badwords_badwordson=true
> [09:08:17] OpenCollar-3.932-full: link_message string: badwords_badwords=test-badword
> [09:08:17] OpenCollar-3.932-full: link_message string: badwords_testword2=penance
> [09:08:17] OpenCollar-3.932-full: link_message string: badwords_penance=tis 's the testpenance!
> [09:08:17] OpenCollar-3.932-full: link_message string: badwords_tis 's the testpenance!=

the problem is with the given dump, one then puts into the defaultsettings NC - 
and with the parsing within the badwords addon as it is done here,
https://github.com/OpenCollar/OpenCollarUpdater/blob/main/LSL/OpenCollar%20-%20badwords.lsl#L411

because even the following, modified line does not really work
`User_badwords=badwordson~true~badwords~test-badword~badwords~testword2~penance~tis 's the testpenance!`
giving only this:

> link_message string: badwords_badwordson=true
> [09:18:53] OpenCollar-3.932-full: link_message string: >badwords_badwords=testword2
> [09:18:53] OpenCollar-3.932-full: link_message string: badwords_penance=tis 's the testpenance!

getting the last badword and working penance
## Suggestion
- lets dump settings this way
  `User_badwords=badwordson~true~badwords~test-badword,testword2,testword3~penance~tis 's the testpenance!`

> link_message string: badwords_badwordson=true
> [09:23:33] OpenCollar-3.932-full: link_message string: badwords_badwords=test-badword,testword2,testword3
> [09:23:33] OpenCollar-3.932-full: link_message string: badwords_penance=tis 's the testpenance!
- and then modify
  https://github.com/OpenCollar/OpenCollarUpdater/blob/main/LSL/OpenCollar%20-%20badwords.lsl#L413
  to this
  `g_lBadWords = llParseString2List(llToLower(sValue), [","], []);`

using above line in _defaultsettings_ NC and this code modification is working even while settings dump still shows it in a different way, after adding a new badword

> User_badwords=badwordson~true~badwords~test-badword~testword2~testword3~testword4~penance~tis 's the testpenance!

I'm also not sure, if this line may need some rework **cosmetic issue**
https://github.com/OpenCollar/OpenCollarUpdater/blob/main/LSL/OpenCollar%20-%20badwords.lsl#L192
as the output after adding a badword is:

> Zopf Resident is forbidden from saying test-badword, testword2, testword3, testword4, or test5
> The penance phrase to clear the punishment anim is 'tis 's the testpenance!'.

while showing them gives

> [10:16:46] OpenCollar-3.932-full: Badwords are: test-badword or testword2 or testword3 or testword4 or test5

**Comment by WendyStarfall** [comment]
Thanks a lot for reporting this in such a detailed way, that's super helpful, thank you

**Comment by RayZopf** [comment]
ok, found the place that is responsible for the settings dump:
https://github.com/OpenCollar/OpenCollarUpdater/blob/main/LSL/OpenCollar%20-%20badwords.lsl#L278

needs to be changed to:
`'llMessageLinked(LINK_SET, LM_SETTING_SAVE, g_sScript + "badwords=" + llDumpList2String(g_lBadWords, ","), NULL_KEY);`

same with
https://github.com/OpenCollar/OpenCollarUpdater/blob/main/LSL/OpenCollar%20-%20badwords.lsl#L331

also
https://github.com/OpenCollar/OpenCollarUpdater/blob/main/LSL/OpenCollar%20-%20badwords.lsl#L344

replace "~" with ","

well.. working on it, testing it - will then request pull/merge

https://github.com/OpenCollar/OpenCollarUpdater/pull/39

**Comment by WendyStarfall** [comment]
#39
