### ISSUE TITLE
Loading the version 3.932 Scripts

### ISSUE THREAD

**Issue by mutepaladin07** [OpenCollar/opencollar#43]
There is a problem with loading your scripts, once you update completely, the actual version manipulates and enlarges the prim that you place them in, sadly this alters the look of the collars i create and is rather annoying. Please fix this issue immediately.

**Comment by WendyStarfall** [comment]
Many designers use the scripts successfully, please look more closely at how the collars are built and ask for help in our OpenCollar R&D group if you get stuck.
