### ISSUE TITLE
3.971 and above: colorizer and titler

### ISSUE THREAD

**Issue by DariaLinette** [OpenCollar/opencollar#442]
There is a "float text" button under colorizer menu, but the sub-functions no longer work. So bad, cause a wide range of colors or shades was available for hover title
From 3.971 [Edit: 3.968 after check] update, there is now a "color" button under apps\titler menu, which totally overrides the former colorizer functions (but offers only basic colors).
Meanwhile, the former float text options are still here under "colorizer", but useless.

So, I'd make 2 alternate suggestions:
- Either restore the colorizer functions for title, and abandon the current titler color system
- Or simply delete them to simplify menus and spare some script weight, and switch to the new title color system for good.

**Comment by WendyStarfall** [comment]
Hi, Daria. You are free to send us a pull request with your suggestions! It would be nice if you refer to issue #442 in the commit title or description. Keep in mind that the logic you are suggesting will add to scripts; methods for profiling can be found in recent commits if you track the history on the main branch.

Alternatives that won't add to script weight:
- give your floattext element a ~nocolor tag
- uninstall the OpenCollar - color.lsl plugin

**Comment by DariaLinette** [comment]
Okay I'll do this. Sorry, I'm still clumsy with github system (^^)
