### ISSUE TITLE
add notecard giver

### ISSUE THREAD

**Issue by hexathos** [OpenCollar/opencollar#443]
Hi,

adding a notecard giver if a notecard named "ownerinfo" (or something similar) exists, would be nice.

so you can add information about isolated wearers their owners etc :)

**Comment by natalja92** [comment]
i would like to enhance the request for a 

<prefix>getinfo command, to receive a short message which is setable by [sec]owner

**Comment by WendyStarfall** [comment]
I might do this stuff as extra plugin but can't see it as part of the standard package, too few people showed interest sadly
