### ISSUE TITLE
OpenCollar - bookmarks version 3.980

### ISSUE THREAD

**Issue by Attitum** [OpenCollar/opencollar#447]
Im under the understanding that Bookarks replaces the old method of adding a LM into a collar to control a subs movements. 
{
       OLD way - Copy LMs to collar in a simple name format such as 001,002.003, 004  you get the idea, then restrict TPs ( LM,LOC,LURE )  thus effectively restricting the subs moves to only what resided in collar

}

{
     NEW Way - Add place 1 2 3 4 5 to a text file or thru menu system print it to make sure you have some places - okay great i do, restrict TPs ( LM,LOC,LURE ) and i am thinking i should be able to goto the locations
}

Result is this
{
     [02:15:56] OpenCollar: Can't teleport due to RLV restrictions
}

Is this thinking wrong or is it a bug ?

**Comment by WendyStarfall** [comment]
The system is behaving correctly with bookmarks. If we have teleport and travel restrictions they cannot be circumvented with a bookmark tp. It was also fixed for the source that still relied on drop-in landmarks with f0e27ab629df35b3275c842b4a0612d1462128d1 for #316

**Comment by laurentf2** [comment]
Still Owners should be treated as exceptions, even in bookmarks, or it defeat the whole usage of it.

**Comment by WendyStarfall** [comment]
Laurent and I had a chat a few hours ago.

The usage case would mean being restricted of travel but _"sent home"_ by the Owner via bookmark nevertheless. My point was that being _"taken home"_ would be based on interaction: Owner goes there first, brings wearer along, then optionally grounds them; no change needed.

Do we want to favour playful interaction in this case or do we want to add clicky convenience of being able to remote-ground someone at arbitrary locations on a whim?

In case changes along those lines would happen, bookmarks must no longer be accessible to group and secondary auth levels.

**Comment by Attitum** [comment]
I don't see why not > bookmarks must no longer be accessible to group and secondary auth levels
Why not >  owner, sec owner, and group
And NOT just anyone [ openaccess ]

This is exactly how the LMs in a collar was being used > The usage case would mean being restricted of travel but "sent home" by the Owner via bookmark, 
IF NOT this i fail to see the point of bookmarks completely considering its 3 clicks to TP from inventory > landmarks.  And many more to TP thru a collar.

**Comment by littlemousy** [comment]
My 2 cents...
If you want your sub to go home on their own, release their teleport restrictions.  If you want to take them home, then go there, and use tplure to bring them to you.

**Comment by laurentf2** [comment]
@Littlemousy and @wendy ... agreed...  but then the bookmark app  is useless : Owner use one click in favorites and another one for sending tp.. but why would one use the bookmark app then ?  

Playful interaction doesn't goes well with RLV restrictions anyway, but still I would like to know what usage was planned for bookmark  ?
