### ISSUE TITLE
Bug in Exceptions Menu

### ISSUE THREAD

**Issue by AlistairBrownlee** [OpenCollar/opencollar#45]
Exceptions menu is bugged. Can not use any of the features in the menu checked or unchecked. Can not Force-TP, can not restrict IMs from owners, etc.

**Comment by WendyStarfall** [comment]
hey, I will need to know please what version of the collar is showing this behaviour.

the exceptions menu had an overhaul for 3.933 which is the latest minor release

**Comment by AlistairBrownlee** [comment]
v3.933. Did an update earlier this week and got a new collar which I updated but still not working.
1. RLVa enabled in Firestorm Preferences.

2.I have script rights on the parcels I frequent. (Some even allow scripts)
3.Set exceptions and permissions for Owners and Second Owners. (Can't set exceptions for individually added avatars even though have permission to do so):

Current Settings for owner: 
Can send them IMs even when blocked.
Can receive their IMs even when blocked.
Can see their Chat even when blocked.
Can see their Emotes even when blocked.
Can receive their Teleport offers even when blocked.
Sub cannot refuse a tp offer from them.

4.Relay set to Auto.
5.Map/TP options all enabled:

LM = Enabled (Teleport to Landmark)
Loc = Enabled (Teleport to Location)
Lure = Enabled (Teleport by Friend)
Map = Enabled (World Map)
Minimap = Enabled (Mini Map)
ShowLoc = Enabled (Current Location)

**Comment by WendyStarfall** [comment]
thanks for reporting this; Medea Destiny is working on some changes in auth, these will be latest available at 3.940

if you have an owner set and you aren't owner yourself, they will need to set the exceptions for you but from what I read you had authorization, so that can't be the problem.. either way this system is going to have bigger changes, sorry if some stuff is acting a bit wonky right now

**Comment by WendyStarfall** [comment]
Exceptions overhaul is completed in 3.934, should solve it :3

**Comment by WendyStarfall** [comment]
Problem is back in 3.936, exceptions failing for Sec Owner and others cannot be added with the error message being "UUID" is not a valid avatar uuid.

**Comment by WendyStarfall** [comment]
Update: I learned from Medea that we get the "UUID" if the request took too long, this is just a small nuisance and people can be added if re-trying.

**Comment by WendyStarfall** [comment]
Update 2: Right so I tested this thoroughly now and what is indeed failing here is that - Sec Owners are not added automatically to the exceptions dealy for Sec owners. It works for Owners, it works for others.

WORKAROUND: For now this can be dealt with by just adding a Sec Owner as Others and setting the Exceptions there. 3.937 will have a fix for that but this time the update may take a while.
