### ISSUE TITLE
Cannot detach collar,

### ISSUE THREAD

**Issue by annmariefranizzi** [OpenCollar/opencollar#453]
This collar as far as i know is not locked on, it is on my avatar and i cannot remove it. Please help

**Comment by WendyStarfall** [comment]
Here are a few steps that should solve this problem for you. Collar version and viewer type would be good to know if you still have troubles after following these steps.
1. Go to your viewer's preferences.
2. Find an option called something like "Allow Remote Scripted Viewer Controls (RLVa)".
3. Uncheck this option, then relog.
4. Find the collar in your worn items inventory tab or right-click it on your neck and detach it.

You can find free and up to date collars or version updaters [here](http://maps.secondlife.com/secondlife/Haven%20VI/231/27/21).

Links and support forms that reach our support team in-world, you can find [on our contact page](http://www.opencollar.at/contact.html).
