### ISSUE TITLE
attach(), on_rez(), state_entry()

### ISSUE THREAD

**Issue by ghost** [OpenCollar/opencollar#459]
some scripts contains:

default
{
    on_rez(integer iParam) { llResetScript(); }
    attach(key kID) {  if (kID) .... }
state_entry() {.....}
}

But if script RESETS at on_rez, attach event don't executed! it's executed only if DETACH!
in this case need check attach at state_entry, which is executed after reset script

**Comment by ghost** [comment]
make simple script:

default
{

```
on_rez(integer param) {  llResetScript(); }

state_entry()  { llSay(0, "State Entry"); }

attach(key kID) {
    if (kID) llSay(0, "Attached.");
    else  llSay(0, "Detached.");
}
```

}

put it in prim, and try attach and detach them...
You can see "State Entry" message when attached and "Detached." when detached
but never see  "Attached."

**Comment by littlemousy** [comment]
What happens if the item gets worn from the ground, not from the inventory?

**Comment by ghost** [comment]
attach event will happen, because on_rez event has occurred before.

**Comment by WendyStarfall** [comment]
let's look at it again during 4.0 tests
