### ISSUE TITLE
3.933 & older : appearance script: MinMaxUnscaled MinMaxScaled BUG

### ISSUE THREAD

**Issue by ghost** [OpenCollar/opencollar#46]
integer MinMaxUnscaled(vector vSize, float fScale)
{
    if (fScale < 1.0)
    {
        if (vSize.x <= 0.01)
            return TRUE;
        if (vSize.y <= 0.01)
            return TRUE;
        if (vSize.z <= 0.01)
            return TRUE;
    }
    else
    {
        if (vSize.x >= 10.0) 
            return TRUE;
        if (vSize.x >= 10.0)      <<<<< this is correct? may be vSize.y  ??
            return TRUE;
        if (vSize.x >= 10.0)      <<<<< this is correct? may be vSize.z  ??
            return TRUE;
    }
    return FALSE;
}

integer MinMaxScaled(vector vSize, float fScale)
{
    if (fScale < 1.0)
    {
        if (vSize.x < 0.01)
            return TRUE;
        if (vSize.y < 0.01)
            return TRUE;
        if (vSize.z < 0.01)
            return TRUE;
    }
    else
    {
        if (vSize.x > 10.0) 
            return TRUE;
        if (vSize.x > 10.0)    <<<<< this is correct? may be vSize.y  ??
            return TRUE;
        if (vSize.x > 10.0)    <<<<< this is correct? may be vSize.z  ??
            return TRUE;
    }
    return FALSE;
}

**Comment by WendyStarfall** [comment]
The x/y/z are correct, calculations here work with tables and they confuse the hell out of everyone.
What matters: it works. :D
