### ISSUE TITLE
3.933 & older : appearance script: Store_StartScaleLoop()  CHECK

### ISSUE THREAD

**Issue by ghost** [OpenCollar/opencollar#47]
Store_StartScaleLoop()
{
    g_lPrimStartSizes = [];
    integer iPrimIndex;
    vector vPrimScale;
    vector vPrimPosit;
    list lPrimParams;
    if (llGetNumberOfPrims()<2) 
    {
        vPrimScale = llGetScale();
        g_lPrimStartSizes += vPrimScale.x;   <<<<< this is correct??? 
    }
    else
    {
        for (iPrimIndex = 1; iPrimIndex <= llGetNumberOfPrims(); iPrimIndex++ )
        {
            lPrimParams = llGetLinkPrimitiveParams( iPrimIndex, [PRIM_SIZE, PRIM_POSITION]);
            vPrimScale=llList2Vector(lPrimParams,0);
            vPrimPosit=(llList2Vector(lPrimParams,1)-llGetRootPosition())/llGetRootRotation();
            g_lPrimStartSizes += [vPrimScale,vPrimPosit];
        }
    }
    g_iScaleFactor = 100;
}

**Comment by WendyStarfall** [comment]
#46
