### ISSUE TITLE
Move Restrictions to a restrict submenu

### ISSUE THREAD

**Issue by masterofsorts** [OpenCollar/opencollar#472]
Might be more cosmetically pleasing to move talk,view,touch,camera,misc to a Restrict submenu from the main RLV menu, this would also allow expansion (i.e add groups subcategory or split out misc) without the RLVmain going to 2 pages.

**Comment by WendyStarfall** [comment]
This sounds very similar to the way disgraced versions handle restrictions. Too similar. I'm not sure if it is really convenient to nest all the individual restriction menus into yet another category tho, there are plenty categories to make use of and a more sophisticated group control should be it's own plugin.
