### ISSUE TITLE
Option to turn Leash Forced rotation off/on

### ISSUE THREAD

**Issue by TerraClaremont** [OpenCollar/opencollar#473]
This may not be a very big issue to many, but the forced rotation from the leash, when debug messages are enabled, floods chat badly. It also makes camera movement while you are following someone a bit odd and jerky. For those of us who would wish to disable this feature, a button in the leash menu to toggle it would be very nice. Thank you!

**Comment by WendyStarfall** [comment]
This feature we once had but, as far as I remember, was broken and we didn't carry it over. Reason for that is that the leash menu already is kind of overwhelming if you consider that so many users really just want to grab it, yank it and in some cases maybe tint their leashes some, oh well, for now you could just comment [line 770](https://github.com/OpenCollar/OpenCollarUpdater/blob/main/LSL/OpenCollar%20-%20leash.lsl#L770) in the leash script. (It will look a bit different in-world, that script, just search for "setrot")

**Comment by WendyStarfall** [comment]
The leash for upcoming 4.0 releases was fine tuned (e176c75125d3558dff09c65b9fadeeb58708e081)for all users who feel the behavior was unpleasant and choppy (I like it much better too now) and I believe @GarvinTwine also reinstated a chat command to fully disable the turning as well (but I can't remember, there was so much we did lol).
