### ISSUE TITLE
enhance leash post command

### ISSUE THREAD

**Issue by natalja92** [OpenCollar/opencollar#478]
Hi,

i would like to suggest an enhancement to the leash/post command.

it would be great if there is a command <prefix>post <uuid> that allows avatars with access to leash to an object if they know the uuid. 

It would be nice if this option will get a menu option too like a dialog box to enter the uuid.

But there is leash post find?
~ sure. but did you ever try to find a post in an heavy object environment with hundres of "object" named objects? ;{

**Comment by littlemousy** [comment]
This can already be done through a chat command: `<prefix>post <uuid of post>`

Assuming there's enough memory spare in the script, and enough space in the menu, I don't see any reason a text box couldn't be programmed to take a UUID for the post.

I'd have though it would be easier to just type the command into the chat window, than to click through the menus to get to a different place where you can type in the same ID.

**Comment by natalja92** [comment]
ok, it is currently not mentioned on http://www.opencollar.at/leash.html and i found nothing on a quick overview of the leash.lsl :D

**Comment by SilkieSabra** [comment]
I added the chat command to the manual, thanks to natalja and mousy!
