### ISSUE TITLE
display active rlv restrictions in a dialog/chat window

### ISSUE THREAD

**Issue by natalja92** [OpenCollar/opencollar#479]
Hi,

i suggest the possibility to display a current wearers rlv restrictions in one dialog and the chat window.

so we can do <prefix>restrictions and get a list like

forbidden to:
- read ims
- send ims

exceptionally allowed to
- teleport

that would bypass the enforcement to click through a dozens of menus to get current restrictions of a wearer.

**Comment by Attitum** [comment]
This is already provided to you by the Firestorm Viewer if you use it.

Goto Menu at top of viewer Select [ RLVa ]
from the drop down select  [ Restrictions ]
- You can even copy and paste back into chat for others :)

**Comment by WendyStarfall** [comment]
Marine's RLV has this as well: active restrictions and exceptions can be print to chat from viewer menu.

EDIT: You could also do a *dump_cache command or Options / Dump Cache which will show restrictions and exceptions set by your OpenCollar scripted device in the settings print.
