### ISSUE TITLE
RLV stopped workign with new update

### ISSUE THREAD

**Issue by aislingod** [OpenCollar/opencollar#48]
Had no issues with my collar up until this last update. The collar comes off when locked and Master cannot access the menu..when we try an earlier collar it works just fine...please help as it is my special collar He bought for me

**Comment by WendyStarfall** [comment]
If you were updating a version below 3.841 you will have to set Owners again. To make extra-sure do this:
1. Find a quiet place.
2. Rez your collar on the ground.
3. Run the update.
4. Wait 20 seconds.
5. Set your Owner (he will have to be nearby and give consent by clicking Yes)
6. Wait 20 seconds.
7. Turn RLV off/on.
8. Pick it up and wear it.
9. Have your Owner unlock/lock it.

You can also just wait until the next major release 3.940 which should fix the annoyance having to sometimes kickstart RLV after fresh updates. Feel free to ask if you have any other questions. =)

**Comment by WendyStarfall** [comment]
3.934 has a new routine to work around having to kickstart rlv \o/
