### ISSUE TITLE
Timer -> Clear RLV

### ISSUE THREAD

**Issue by KarinKorpov** [OpenCollar/opencollar#482]
Seems that the option Clear RLV with a timer not works like belongs

After the timer that reset the collar and relocks.. but the restrictions stays
can someone check for me?

**Comment by littlemousy** [comment]
Yup, that looks like a bug to me.  if you can, try editing the timer script in your collar to include the change I made in the commit listed here.  If you can't, drop me a line in-world and I'll get an updated script to you.

**Comment by KarinKorpov** [comment]
Thanks little mousy, it works indeed. 
I have the scripts on my site changed
