### ISSUE TITLE
Lure TP while using forced sit (Ctrl+alt+S) locks the avatar in place at the destination

### ISSUE THREAD

**Issue by ghost** [OpenCollar/opencollar#489]
Everything is on the title.
When i sit on the ground using the forced sit keyboard shortcut, and get teleported with the collar, i arrive already sitting at my destination, but the avatar is locked in place.
the "stand" button dissapears when pressed, as usual, but the avatar doesnt stand up.
"Stop avatar animations" doesnt work since force sit isnt really an animation so to speak. I tried all commands on the avatar health menu, also tried edit shape.. but the only solution to get unlocked is to relog.
Friends that use other collar scripts dont have that issue.
My collar runs OC version 3.973 (still has to update).

**Comment by littlemousy** [comment]
I'm not sure where to start looking for this problem.  TP lure is a viewer function, (ctrl+alt+s) is a viewer function.  I don't havce a collar that old handy to test with.  Could you try to replicate the problem with a newer collar (and maybe even with no collar) to check its not been fixed already.  Does anyone else see this problem?

**Comment by WendyStarfall** [comment]
This cannot be related to the collar. However, I tried anyway and couldn't observe this behaviour on Firestorm 32-bit 4.6.7.42398 (win) with OpenCollar 3.992 and for comparison with Disgraced 1.7.4.

What happens to you, will also happen if you ctrl+alt+s sit and manually accept a teleport request.

**Comment by ghost** [comment]
i never tried without collar, but i will give it a go, also for the TP request vs collar TP.
