### ISSUE TITLE
Request: Restore Last Saved Settings

### ISSUE THREAD

**Issue by natalja92** [OpenCollar/opencollar#492]
Hi,

this affects many, many public collars. Whenever something is changed by strangers, it took ages to reset the collar to the desired settings.

Please give Owners the possibility to create a settingstemplate, that the wearer can load to restore / reset settings without the need to setup whole #rlv folders again, or access rights. 

Yes there is the defaultsettings nc... but setting that up requires much manual work, and a land to rez the collar. And it has the sideeffect, that those settings are fixed. But sometimes we change minor settings (rlv restraints for example, or rlv-detach-settings in #rlv) and doing this will take much time and requires actions from both (owner+wearer) 

with a menufunction to backup the settings to a notecard (eg lastsettings) opencollar can give us the joy of much less work and usability :)

**Comment by littlemousy** [comment]
Unfortunately, SecondLife servers don't allow scripts to write to notecards in the way that some OpenSim servers do.  With the current SecondLife servers, writing settings to a notecard has to be a manual process.

The default settings card can be edited without having to rez the collar.  The collar's stored settings can be dumped to chat, and copy/pasted into the notecard.  The steps are as follows:
1) say <prefix>dump_cache
2) copy the resulting text to the clipboard
3) right click and edit the collar
4) open the defaultsettings notecard
5) select all, and paste the new settings over the old ones
6) save and close the notecard

It would certainly be convenient to have this available from a menu, it may be possible to add this while updating the settings script for version 4, but storing an additional set of settings may prove too much to store in a single script.  As with so many things in OpenCollar, this would be easier if database storage was available.

**Comment by WendyStarfall** [comment]
There are various ways to do this without becoming dependent on database storage solutions.

Last summer @SumiPerl explored ways to store and recall data from pastebins. The same would be possible with forks of this repository and methods in scripts are already present to query small information from text or "raw" files on the web.

Either of these solution will require at least a bit of manual input and where it is possible to write to pastebins remotely, to the best of my knowledge this cannot reliably happen in rapid succession.

Considering the fickle nature of most of these role plays, setting, printing and pasting sounds like an acceptable cost free method much in favor over becoming dependent on some PaaS or server solution.

A simple solution for creating setting templates without having to unlock and remove the device while the user stays fully in control over how and where those settings are stored.

In 4.0 versions the settings script is so tiny, it can be modified to make all this happen. :)
