### ISSUE TITLE
"tpto:<coordinates>=force" command no longer excecuted

### ISSUE THREAD

**Issue by ml132** [OpenCollar/opencollar#495]
This command used to be processed in "rlvtp.lsl." This script got moved to "rlvstuff.lsl" and the teleport forcing code got dropped. I also noticed the newest version of the owner hud no longer has "teleport to me" or "teleport to camera" as well. Was this change intentional?

**Comment by littlemousy** [comment]
tpto:<coordinates>=force should now handled by the bookmarks plugin

**Comment by ml132** [comment]
Check [line 206 of the bookmarks plugin](https://github.com/OpenCollar/OpenCollarUpdater/blob/main/LSL/OpenCollar%20-%20bookmarks.lsl#L206). It's commented out:

```
if (llSubStringIndex(sCmd,"o:") == 0) {}//llMessageLinked(LINK_SET, RLV_CMD, "tpt"+sCmd, kID); (enable this to support hud forcetp. disabled now since rlvtp still does this
```
