### ISSUE TITLE
RLV Inventory restriction on open collar

### ISSUE THREAD

**Issue by drecco** [OpenCollar/opencollar#5]
I have noticed in 3 different avatars, over several OC update versions from 3.8 to 3.916 that using RLV to restrict inventory on OpenCollar in Singularity Viewer causes the avatar to be immediately logged out of world.

**Comment by WendyStarfall** [comment]
Hi drecco, this problem has to be somewhere on the Singularity Viewer's end; here is how they will help you:
1. Reproduce the crash and acquire the logs as described here: http://community.secondlife.com/t5/English-Knowledge-Base/How-to-report-a-bug/ta-p/733545#Section_.3
2. Create a new issue on the Singularity tracker and paste the log: http://code.google.com/p/singularity-viewer/issues/list
3. I'm not sure who is the most active dev at the moment in the Singularity project but I believe that would be Latif Khalifa; also the most recent sauce is in his repo here: https://github.com/lkalif/SingularityViewer

I tried to reproduce it myself but so far I had no issues on RLVa 1.4.8 with inventory restrictions but didn't try on Singularity. I hope things will be fixed for you soon, drecco. Good luck! =)
