### ISSUE TITLE
@emote was an exception to emote truncation 

### ISSUE THREAD

**Issue by CorwinDavidson** [OpenCollar/opencollar#52]
The @emote removal removed an EXCEPTION to the emote truncation.

When @sendchat is enabled emotes are truncated to 15 characters.  The @emote=add would enable an exception to this truncation and allow for full length emotes (barring special characters) even when chat was not allowed.

**Comment by WendyStarfall** [comment]
thanks a lot but has been fixed already with 048e9ce85e9cde1e55f6790b360e5056f88b45bb

**Comment by CorwinDavidson** [comment]
Perhaps you misunderstood.

 your FIX ..  BREAKS functionality

The code as it was before the "FIX" was applied allowed an owner to let their sub / slave to have longer emotes when local chat was disabled.  the "FIX" removed that function.

To clarify.

Use a collar without the Fix applied.  Disable Local Chat and Emote a line longer than 15 characters.  It will be truncated to 15 character.

Enable the Long Emotes, while still keeping Local Chat Disabled,  then emote a line longer than 15 characters.  It will not truncate unless you use a restricted symbol (as per the RLV API)

The @emote has no effect on emote length when local chat is not disabled.

**Comment by WendyStarfall** [comment]
Going to test it soon, thanks!! It's just that after removing the @emote routine we can apply all / lift all just fine. I'm a bit trigger-happy with fixes that work because we will have to review RLV features in total anyway for OC4.

**Comment by WendyStarfall** [comment]
Tested, fix works well for what it is supposed to do. If we get a lot of requests for the "long emote" dealy, we can bring a working routine back but I really think this is something gags should play and will play for most people, the collar is doing it even not as perfect as a real gag would.

**Comment by WendyStarfall** [comment]
brought it to the table and rolled rlvtalk back with 89de9f846f93cd2e2d219679b1da0df333e4c59d
that means I'm going to mess around with rlvtalk partly for 3.936 myself and Medea will do the more sophisticated work on it and wrap it up for 3.937, we will keep the routine but improve usability for the overall menu and handling of the exception to allow for >16 characters emotes
