### ISSUE TITLE
3.997 parses regex/wildcard

### ISSUE THREAD

**Issue by KreaSmadga** [OpenCollar/opencollar#524]
That just happened to me

`[09:27:01] ღƐɱι ℜσχℓєץ ღ (emiko.mode): *+.+*TOMORROW IS NOT LOOKING GOOD EITHER*+.+*`

rlv debug message:
`[09:27:01] <mycollar>:  executes: @findfolders:.+*tomorrow is not looking good either*+.+*=7373541`

that should not happen afaik

`[09:29:25] <mycollar>: I am running OpenCollar version 3.997`

as a proof on Haven VI i did 
/1 *version
and got some responses, oldest was a version 3.968

**Comment by WendyStarfall** [comment]
Hi, the asterisk character is a wildcard prefix, that's how all collars would perk up, check it if the one issued the wildcard is authorized and if so, like on public access, forward the command. The other wildcard is the hashtag, that one especially exempts the avatar who used it.

`/me shouts: #booty`
`/me shouts: #grab`
`Hee! I leash lots of ppl who do funny thing with their butt XD`

If you want to tweak your own kit to behave differently, you can do that [here](https://github.com/OpenCollar/OpenCollarUpdater/blob/main/LSL/OpenCollar%20-%20listener.lsl#L395). This will be on line 389 if you are looking at the listener script in-world in current 3.997 patches.

Suggestions for alternatives to improve this in future versions:

**Family Prefix:** _Chose a prefix for your whole family!_

"Finally I can leash my whole family with one command and don't have to worry anymore when using asterisk characters and hashtags in obnoxious gestures and for emotive rollplay as my native language is not English and I constantly do for some reason `*smile and giggle*`"

**Unicode Prefix:** _Choose a prefix so difficult nobody can type or memorize it!_

"I always wanted to Alt +262D to make everyone do the same. We can all be equal now."

**Wendy's Prefix of Fluffypower:** _Become totally irritated by something that makes entirely no sense!_

"Max integer [burrito](http://upload.wikimedia.org/wikipedia/commons/0/07/Euler_Diagram.svg)."

**Comment by KreaSmadga** [comment]
One should mention that a public chat command like *version COULD be a security risk as it may reveal possible useable bugs and rabbitholes ...

**Comment by GarvinTwine** [comment]
It is only public if the collar wearer sets the collar to public access else you get no reply at all.
Compared to be able to just IM someone with @version to see if and if yes which rlv version is used, i find this rather uncritical besides i doubt there are many who even know about this command as it is not mentioned in the manual. 
But thank you for your concerns we will think if the danger of misuse of this "command" is bigger than the use of someone who tries to help and knows this command for that reason and eventual make it Trusted (secowner) & owner & wearer only.
