### ISSUE TITLE
OpenCollar 3.935 - Animations: bugs!!!

### ISSUE THREAD

**Issue by ghost** [OpenCollar/opencollar#53]
Menu Animations: 
"AO ON" "AO OFF" "Give AO"  buttons don't work

Pose animations stops after a few seconds

**Comment by WendyStarfall** [comment]
You need a compatible AO for this to work. The description for this is in the menu text above the buttons. I tested the network for the "Give AO" function and it's distributing Sub AOs through the collar menu correctly. Alternatively you can try Medea's beta drop-in compatibility script which you can get in the OpenCollar Chatter group notices. (Note: For this to work your AO must be ZHAOII or Oracul based!)

**Comment by ghost** [comment]
I'm testing Collar with SubAO 3.600

OpenCollar - anim 3.935:

576        g_lAnimButtons = [" Pose", g_sTriggerAO, g_sGiveAO, "AO ON", "AO OFF"];
.....
620        g_lAnimButtons = [" Pose", g_sTriggerAO, g_sGiveAO, "AO ON", "AO OFF"];

.....

730        else if (~llListFindList(g_lAnimButtons, [sMessage]))
              { // SA: can be child scripts menus, not handled in UserCommand()
                     llMessageLinked(LINK_SET, iAuth, "menu " + sMessage, kAv);
              }
              else *********\* function from above intercept all "g_lAnimButtons" containing "Give AO" "AO ON" and "AO OFF", and functions from below don't work
                   {
                        if (sMessage == g_sGiveAO)
                        { //queue a delivery
                              DeliverAO(kAv);
                        }
                        else if(sMessage == "AO ON")
                        {
                              UserCommand(iAuth, "ao on", kAv);
                        }
                        else if(sMessage == "AO OFF" )
                        {
                               UserCommand(iAuth, "ao off", kAv);
                        }

**Comment by WendyStarfall** [comment]
I've been able to reproduce this bug. Integrations and receiving the AO menu works fine, the on/off buttons are borked.
