### ISSUE TITLE
subao+collar dialog opens wrong

### ISSUE THREAD

**Issue by KreaSmadga** [OpenCollar/opencollar#530]
Hi, i am currently using OpenCollar 3.997 with subao got tonight. subao was locked by owner. 

owner clicked ksmenu -> animations -> ao menu -> more -> pose

the following menu opened on MY screen, but it should open on user who accesses my collar.

```
[17:44] ..::YF::.. Dakota Collar (A) v.X4: Settings (Designer defaults, followed by User Entries)
The below can be copied and pasted to "defaultsettings" notecard
Replacing old entries, but must include Designer defaults (if present):

#---My Settings---#
User_Global=locked~1~touchNotify~1
User_auth=<removed>
User_auth=blacklist~<removed>
User_rlvmain=on~1
User_rlvrelay=settings~mode:159
User_rlvundress=smartstrip~1
User_leash=leashlength~2
User_leashParticle=Size~<0.1,0.1,1>~Color~<0,0,0>
User_anim=PoseMoveWalk~~walk_Female~PoseMoveRun~~run_Female
```

**Comment by WendyStarfall** [comment]
We would have to make a change in the Submissive AO scripts, it would be nice if the issue can be posted here, please: https://github.com/OpenCollar/OpenCollarAO/issues

For a quick fix, the "MORE" button could just re-menu to the AO Menu if authed by anyone else than wearer with notify that the Sub AO Quickmenu is really for collar wearers. A nicer fix could be to direct non wearers back to the Animations menu in the collar, however that will be more complicated to do.

If you want to give the a non-conservative approach a shot, maybe a first incision could be made here -> https://github.com/OpenCollar/OpenCollarAO/blob/beta/LSL/OpenCollarZHAOII%20-%20Interface.lsl#L609
