### ISSUE TITLE
 [script:OpenCollar - subspy] Script run-time error Stack-Heap Collision

### ISSUE THREAD

**Issue by HisPhaedra** [OpenCollar/opencollar#54]
When the subspy feature for listening is turned on there is a problem that keeps happening over a course of a few hours and it ends with a " [script:OpenCollar - subspy] Script run-time error Stack-Heap Collision" that occurs and the owner no longer recieves the sub's chat. This never happened on the previous version of the collar.. it just seems to be happening now that I have updated to 3.935 which leads to an unhappy, Master.  Please help!

When he's not happy ain't nobody happy!

**Comment by WendyStarfall** [comment]
Outch, that's bad. Our main contributor to subspy took off for over a week to take a break. I'll see what I can figure out on my own by tracking back the last changes. What would be super helpful was if you told me what version you ran before.

**Comment by HisPhaedra** [comment]
Yes big ouch!! My Master has not been pleased. I was running version 3.8 before and never had that issue and he had it set to report to him every 10 minutes I believe.

**Comment by WendyStarfall** [comment]
Maybe during 3.8 versions you just typed shorter chat. There weren't any changes in this part of the script /at all/, so that can't be the reason.

**Comment by HisPhaedra** [comment]
In 3.8 I would have hours (even days without my Master logging on) of long text and never had the issues I'm having now. It can be as fast an hour or two with not so much chat. I am not the only one. My chain sister as well is having the same problem.

**Comment by HisPhaedra** [comment]
Again.. it's been not even an hour and I've recieved the error and my chat has stopped.  [script:OpenCollar - subspy 3.935] Script run-time error
Stack-Heap Collision

I'm not sure what is causing it but it has to be something with the new update. It only took 36 minutes this time for it to come up.

**Comment by RayZopf** [comment]
some kind of workaround for the current version: set radar timer to the shortest timespan and keep your fingers crossed... also try to write less/shorter messages
As i'm unable to figure out what exactly causes that heap collision, i just modified the addon to cap messages that are too long (only 450 chars, sry) and also sent unsheduled reports when a certain limit is reached (1000 chars) to make above fault less likely.

btw: currently (and in v 3.8) the oldest message lines just get discarded when 1500 chars are reached (and no report was on shedule before that happens)

**Comment by HisPhaedra** [comment]
It was tried, my chain sis who works with scripts even changed it so it could report every 2 minutes and it was no good still got the error quickly. So I downgraded my collar back to 3.8 to get it to work. So far haven't had a single issue with it. I don't like how the menu lists spam local but if's that's the only thing I have to worry about to get the listener on chat to work.. I can deal with it. It would be nice though to know why it is that it's happening on the 3.935 version and never on the 3.8.

**Comment by WendyStarfall** [comment]
3.936 released, that should solve it
