### ISSUE TITLE
When RLV is off, the collar INFINITELY SENDS a message that RLV is off

### ISSUE THREAD

**Issue by donelson52** [OpenCollar/opencollar#540]
Once is enough, thanks.

**Comment by GarvinTwine** [comment]
obviously not as you dont even do what the message tells you to do but you
do the effort to get here and complain... to turn rlv off and it shows you
exactly what to type (or copy paste).
things can be easy when you just read and do what messages say.

**Comment by donelson52** [comment]
I keep getting emails from it. It's not my collar. I can't do ANY of what you suggested.

There is no need for it to keep repeating the message. 

So how about you get the code's ego in check, and have it say it only once, instead of nagging like a 5-yr old child.

**Comment by GarvinTwine** [comment]
alrite i will change the code that you get from ever collar emails in the
future
\and this service is as well as all , free of charge for yu

**Comment by RayZopf** [comment]
how about stating collar version first?

if it is not your collar who else wears it? asuming you are owner or secowner on it either make the wearer turn on RLV or follow the instruction else maybe get yourself off the collar

**Comment by donelson52** [comment]
Ray, I have sent IMs to this person about this collar, to no avail.

Thanks, Garvin.

**Comment by RayZopf** [comment]
then mute or block the sender / the sending object

collar tells that RLV is off for a reason on every single login

**Comment by WendyStarfall** [comment]
Hi @donelson52 , what you describe in the issue title is not behaviour of OpenCollar stock versions.

Stock versions behave as follows:
- [test the wearers RLV version in granulars](https://github.com/OpenCollar/opencollar/blob/main/LSL/OpenCollar%20-%20rlvmain.lsl#L682)
- [inform the wearer how to disable the test and RLV in the device](https://github.com/OpenCollar/opencollar/blob/main/LSL/OpenCollar%20-%20rlvmain.lsl#L684)
- [inform avatars listed with owner access that the wearer has RLV disabled for this session](https://github.com/OpenCollar/opencollar/blob/main/LSL/OpenCollar%20-%20rlvmain.lsl#L697)

The device doesn't send infinite messages.

@RayZopf 's advice to block the offending avatar works if somebody else wears the device
@GarvinTwine 's advice to disabled RLV in the OpenCollar menu works if you wear the device
