### ISSUE TITLE
Misleading notify when wearer sets self as owner twice

### ISSUE THREAD

**Issue by WendyStarfall** [OpenCollar/opencollar#551]
Reporter: Eva Ryan

Device: OpenCollar 4.0 I BETA
Version: 20150712.1

Steps:
- Wear the factory-reset device
- Add yourself as owner via chat or menu
- Add yourself as owner via chat or menu again

Result: Could not find any avatars starting with "Firstname Lastname" in this region.

This message happens when:
- the agent is indeed not in the region and
- the agent is already listed with the access role of choice

We also still notify with "Could not find any avatars in this region." when adding someone and they were the last not listed agent in this region. We should get rid of these notifies, they inform about the obvious, worded in a way that makes the user believe something went wrong.

**Comment by WendyStarfall** [comment]
Our thingy happens at line [539 - 549](https://github.com/OpenCollar/opencollar/blob/master/src/collar/oc_dialog.lsl#L539):

``` LSL
numAgents = llGetListLength(agentList);
                if (!numAgents) {
                    string findNotify;
                    if (find != "") findNotify = "starting with \"" + find + "\" ";
                    llInstantMessage(kRCPT, "Could not find any avatars "+ findNotify + "in this region.");
                } else {
                    //Debug("Found avatars:"+llDumpList2String(agentList,","));
                    g_iSelectAviMenu = TRUE;
                    ClearUser(kRCPT);
                    Dialog(kRCPT, "\nChoose the person you like to add:\n", agentList, [UPMENU], 0, kID, -1, iAuth, "getavi_|"+REQ+"|"+TYPE); //iDigits==-1 means dialog should calculate numbered dialogs
                }
```

That stuff was merged from "OpenCollar - getavi.lsl" into oc_dialog.lsl by @littlemousy during the 3.9 API phase sometime in spring 2014. I remember at the time we would discuss if we should keep or drop this message we used to have: "You are the only one in this region. Add yourself?" and eventually did that later down the road.

Suggestion:
- If we keep a notify when an agent couldn't be found, let's notify that an agent couldn't be found.
- If an agent is already on the list, let's notify they are already on the list.

How about that?  :cake:

**Comment by GarvinTwine** [comment]
already working on this (actually done in world)

**Comment by GarvinTwine** [comment]
OK this one got a bit chaotic :( ...
Romka's solution is perfect here, lets take his and revoke mines.
Then i will add my additional changes.

**Comment by WendyStarfall** [comment]
> [2015/07/19 05:23]  Name Redacted: (Saved Sun Jul 19 06:24:09 2015)Set myself as owner on the new collar.. this is the result.
> [2015/07/19 05:23]  Name Redacted: (Saved Sun Jul 19 06:24:12 2015)[21:22:07] Name Redacted: naowner Name Redacted
> [21:22:15] OpenCollar 4.0 BETA - Part II: 
> 
> Congratulations, you own yourself now.
> 
> [21:22:15] OpenCollar 4.0 BETA - Part II: Could not find any avatars in this region

Otto should do the rest of the job. The problem with this notify is in the re-menu. While it behaves now correctly, it will still notify when trying to re-menu to the get avi dialog. If we can't make it do how it won't irritate users, we could still go with my "non conservative approach". *reach for scalpel and swabs*

**Comment by GarvinTwine** [comment]
i think they major fix for this is in #580 : 
removed the remenu to choose avatars after selecting one as
owner/trusted/blocked in favor to go back to the access menu (this
should prevent any unneeded and irritating notifies after adding oneself
or an owner and no one else is around)
one more change to more clear notifies in dialog script coming up

**Comment by GarvinTwine** [comment]
#581 should fix this for once and all:
When nobody is around but avatars already in lists, the message wont be:
"No avatars in parcel found" but "No avatars found that are not already
listed : [URIs]"
Also sending a "BACK" to reopen the Access menu when nobody new was
found.

**Comment by GarvinTwine** [comment]
#586 fixes a bug in dialog which was introduced in the earlier commit
