### ISSUE TITLE
llInstantMessage in oc_dialog

### ISSUE THREAD

**Issue by GarvinTwine** [OpenCollar/opencollar#557]
I came across a llInstantMessage in the dilaog script, line 542. 
Should be changed of course to llMessageLinked(-1,NOTIFY,msg,key)

**Comment by WendyStarfall** [comment]
is related to #551

**Comment by WendyStarfall** [comment]
Got in my e-mail that I received an inventory offer with your edit.

PS: I couldn't log on today, will try again in about 10 hours from now!

**Comment by GarvinTwine** [comment]
replaced the llInstantMessage with OC standard LM.
Added a filter for DisplayNames, so when you search for part of the
DisplayName this is used as filter and compared now

![b99222e0d7274e60165afec940d181c7](https://cloud.githubusercontent.com/assets/10353806/8720988/b77dec18-2be0-11e5-85d8-68f936d9298e.png)
