### ISSUE TITLE
bug in subhug timing

### ISSUE THREAD

**Issue by SilkieSabra** [OpenCollar/opencollar#56]
From Eve Keneinan:  This is a bug in 3.930 and 3.935.  It is the subhug animation.  The time, if set to greater than 20 seconds, defaults to 20 seconds regardless of the setting.  It can be set to 10 seconds and none of the other couples anims do this.  I've tried it on two collars so far.   If anyone can set their subhug on 60 seconds and check if it ends after only 20, we can confirm more widely.

**Comment by WendyStarfall** [comment]
Yep, that's because the subhug animation isn't looped. I have a replacement ready for 3.938 (the old kneelhug) and a folder ready to pass to people who want to have it right away cause release will take a bit longer this time.

**Comment by NorthGlenwalker** [comment]
An update from the person who found this but could not post herself - ~bottom and ~top animations are non looping and maybe others
