### ISSUE TITLE
Problem on kidnap

### ISSUE THREAD

**Issue by ghost** [OpenCollar/opencollar#560]
You can kidnap someone even if you are not near of the victim. They are no risk to fail for the kidnapper. 

Exemple of mod on doCapture function in oc.disgraced.kidnap  The kidnaper have to at no more than 3 Meters of the victim.

A D100 is lauch for see if the kidnapping fail or not. 

doCapture(key kKidnapper, string sKidnapper, integer iIsConfirmed) {
    if (llGetListLength(g_lTempOwners)) {
        llMessageLinked(LINK_SET,NOTIFY,"0"+"%WEARERNAME% is already kidnapped, try another time.",kKidnapper);
        return;
    }

```
if (llVecDist(llList2Vector(llGetObjectDetails( kKidnapper,[OBJECT_POS] ),0),llGetPos()) > 3 ) { 
            llMessageLinked(LINK_SET,NOTIFY,"0"+"You could kidnap %WEARERNAME% if you get a bit closer.",kKidnapper);
            return;
    }

if (llFrand(100) < 50.0) {
     llMessageLinked(LINK_SET,NOTIFY,"0"+"You try to kidnap %WEARERNAME% , but you fail. Wait a while before try again.",kKidnapper);
        llMessageLinked(LINK_SET, NOTIFY, "0"+" "+NameURI(kKidnapper)+" try to kidnap you but it's fail.Please RP the situation.",g_kWearer);
            return;
}


if (!iIsConfirmed) {
    Dialog(g_kWearer, "\nsecondlife:///app/agent/"+(string)kKidnapper+"/about wants to kidnap you...", ["Allow","Reject"], ["BACK"], 0, CMD_WEARER, "AllowKidnapMenu", kKidnapper, sKidnapper);
}
else {
    llMessageLinked(LINK_SET, CMD_OWNER, "follow " + (string)kKidnapper, kKidnapper);
    llMessageLinked(LINK_SET, CMD_OWNER, "yank", kKidnapper);
    llMessageLinked(LINK_SET, NOTIFY, "0"+"You are at "+NameURI(kKidnapper)+"'s whim.",g_kWearer);
    llMessageLinked(LINK_SET, NOTIFY, "0"+"%WEARERNAME% is at your mercy.\n\n/%CHANNEL%%PREFIX%menu\n/%CHANNEL%%PREFIX%pose\n/%CHANNEL%%PREFIX_restrictions\n/%CHANNEL%%PREFIX_sit\n/%CHANNEL%%PREFIX%help\n\nNOTE: During kidnap RP %WEARERNAME% cannot refuse your teleport offers and you will keep full control. To end the kidnapping, please type: /%CHANNEL%%PREFIX%kidnap release\n\nHave fun!\n", kKidnapper);
    g_lTempOwners+=[kKidnapper,sKidnapper];
    saveTempOwners();
    llSetTimerEvent(0.0);
}
```

}

**Comment by GarvinTwine** [comment]
Thanks, 
good call and I do agree that the physical distance between kidnapper and kidnappee should be taken in account and add your first addition with a distance of 10m which is Whisper range.

On the randomizing fail/success... this needs some discussion imho:
What's the point if someone wants to kidnap if she/he has to try once or 3 times, it's only clicking anyway... if you want to roleplay you roleplay and really do not need the collar to spam messages around when one tries and a random generator says "you fail".

Anyway if we agreed on this there are further options to discuss:
1) Is it random failing only if vulnerable or always (when not vulnerable the wearer can deny to be kidnapped anyway). 
2) Does the odds to succeed change by distance?  (e.g.: starting at 10m with a chance of 1:3 to succeed, 8m - 2:3, 6m - 3:3, 4m 3:2.  2m - 3:1 as best value)
3) Do make a guess the number game out of this:
1-10 when 10m and 1- distance in meters when closer....

**Comment by WendyStarfall** [comment]
Maybe odds could also depend on which "body part" is grabbed. Kidnap-responders and attachment auth would be required for this. Drop'n'go scripts for hair and clothes are not suited as most of these are rigged mesh and can't be touched in the first place. However, they could be plain, simple invisible spheres or boxes, with kidnap odds in their description: kidnap~80%, kidnap~50%, kidnap~20%, ..

This feature should be kept basic as standard variation though. This way users aren't overwhelmed and can create their own mods and quirks for it. Attachment auth and kidnap-responders might be handy.
