### ISSUE TITLE
The Tale of the Self-owned Wearer

### ISSUE THREAD

**Issue by WendyStarfall** [OpenCollar/opencollar#566]
Even with a stronger "secondary" auth role with Trusted in 4.0 devices, we should provide a more simple and convenient method for both Owner and Wearer to grant Wearer primary access even with primary owners set.

This is a strait-forward job:
- Swap the LimitRange [  ] button with a Self [  ] button
- Add a command for pwning urself
- Authorize this command to Owner
- Make the Self [  ] button toggle this command

LimitRange will then only be available as a chat command. I'm confident our users can live with that! :cake:

**Comment by WendyStarfall** [comment]
~~Let's add a setting!~~

**Comment by WendyStarfall** [comment]
If I think about it, adding a boolean-ish setting for this is not so great. I had a chance to briefly test the edit and really like how it added my name and id to settings. It works great that way. Fast. Flawless.

Let's keep it this way! Taking into consideration here that users who generally always added themselves, would always do with name and id in the card anyway and if we change it, they cannot do how they knew they could and we all know what happens then... :speak_no_evil:

However, other boolean-ish settings and such coming from auth will need to pass the test.

I opened a new issue for that. #569

**Comment by ghost** [comment]
Self-owned option seems strange to me...
This renders meaningless the master-slave roleplay, I think... I may be wrong.
