### ISSUE TITLE
Timer bug

### ISSUE THREAD

**Issue by TanyaWibault** [OpenCollar/opencollar#60]
if someone sets a timer in the collar, say the online timer, and later someone comes along and hits the both timer button without setting a RL timer it messes up the timer. You get double menus that neither work and sometimes the sub can access the collar, sometimes they can't. You can't adjust the timers or stop them until you uncheck the both timer button, which if you don't notice it is check you have no idea what's going on. This is probably cause because one timer is at 0 and the other timer is set.

The both timer button should be disabled when only one timer is running or just remove that silly RL timer all together. What use is a timer if all you have to do is log out till it expires :)

**Comment by WendyStarfall** [comment]
Looks I misunderstood something about the new timer feature, what might be coming is a way to more easily implement a slimmer timer and a few other auth specific things. For now, I think it is best to have broken functionality in the old timer switched off and we can still decide if to fix this variation of it or not.

**Comment by WhiteFire-Sondergaard** [comment]
The RL timer is more commonly used than the online timer. It's main purpose is saying: stay in this toy for X RL time, which is pretty common.

**Comment by timberwoof** [comment]
I miss the RL timer.
