### ISSUE TITLE
The story about the RLV and what it said to me when it came out of the box...

### ISSUE THREAD

**Issue by WendyStarfall** [OpenCollar/opencollar#602]
Here is something:

RLV in later 3.99x versions turns itself on out of the box.

This is good! Most users have RLV running in the viewer and will want the collar to work with it right away.

However, while it turns itself on like a good, little RLV, it will not stay on if the device is detached and re-attached unless the switch was flipped off/on.

That is mostly because nobody acknowledged the RLV for already running out of the box.

We should do that by all means and tell the settings that RLV was really good and turned itself on!

**Comment by GarvinTwine** [comment]
added the saving of g_iRLVOn on state_entry to ensure on next rez the RLVState is correctly reinstated in #603
