### ISSUE TITLE
Floating text bug

### ISSUE THREAD

**Issue by imstormy1** [OpenCollar/opencollar#62]
i have turian collar, OC scripted. When i try to use the floating text, it elongates the leash ring on my collar to where it stands out farther than my shoulders. The text appears in white above my head but the leash ring gets huge and stretched thin, so i cant use the floating text feature i guess

**Comment by ghost** [comment]
Check collar for exist "hovertext prim" with description: FloatText~notexture~nohide ,
(prim is invisible)
if prim exist, try reset script OpenCollar - hovertext

**Comment by WendyStarfall** [comment]
That's right.

The collar will need it's extra little prim that produces the Hover Text and this little prim will stretch out if text is displayed so we can keep it above the heads. Sadly some creators forget about adding this prim.

Here is how you can fix that on your own:
1. Make a new box and name it FloatText
2. In it's description put what Romka said: FloatText~notexture~nohide
3. Shrink the box down to around 0.02, 0.02, 0.02
4. Move it into the center of your Turian design
5. Link the box to the collar (don't link the collar to the box or the box will become the root!)
6. Give it a cold boot as in right-click Edit -> Scripts -> Reset Scripts in Selection

That would be all! Keep in mind if you cold boot the collar you will need to re-add owners. You can work around that by first going to Options -> Dump Cache and paste the following string into the defaultsettings notecard:

User_auth=owner~UUID,Firstname Lastname

**Comment by WendyStarfall** [comment]
So.. I've been asking myself, do we really need the hover text prim to expand?
Benefits would be that the hover text is "click-able", do we really need that?
Let's look into it on the way to 3.960 =)

**Comment by ghost** [comment]
no need clickable hovertext prim.
but if not expand prim, hovertext place too low. 
i slice hovertext prim B=0.490 E=0.510 and it "hide" inside collar when expanded

OpenCollar - hovertext:

79    ShowText(string sNewText) {
......
86        params += [PRIM_SIZE, g_vShowScale, PRIM_SLICE, < 0.490, 0.510, 0.0 > ]; 

93 HideText() {
.....
97        params += [PRIM_SIZE, g_vHideScale, PRIM_SLICE, < 0.0, 1.0, 0.0 > ];  // if need 'unslice'

**Comment by WendyStarfall** [comment]
Oh wow! That's clever, let's put that in the script!
