### ISSUE TITLE
constant bell in crouch mode

### ISSUE THREAD

**Issue by GreenTopaz** [OpenCollar/opencollar#622]
bell sounds constantly in crouch mode. i using crouch toggle mode for crawling and it really annoying.
so i did remove **CONTROL_DOWN** from **control** state of _bell_ script.

**Comment by GarvinTwine** [comment]
first which collar version do you use here.
second, what does crouch toggle mode do?

**Comment by GreenTopaz** [comment]
i using 3.997 version and tried 4 beta.
crouch toggle mode changes method of crouching from hold down for crouch to toggle crouch by press down once

**Comment by WendyStarfall** [comment]
This is no longer the case in 4.0 versions of the bell plugin

EDIT: Removing the CONTROL_DOWN flag is a workaround if you do this a lot on 3.9 API by the way!

**Comment by GreenTopaz** [comment]
while crouching and not moving, bell shouldn`t sound, so CONTROL_DOWN flag is useless anyway
btw, **if ((nHeld & (CONTROL_FWD|CONTROL_BACK)) && (llGetAgentInfo(g_kWearer) & AGENT_ALWAYS_RUN)) {** here u use only forward and back flags, so while strafing left-right bell will not sound yes?

**Comment by WendyStarfall** [comment]
It fits for 4.0 bells where we don't play constant loops on input but in the 3.9 bell this is a big nuisance.
