### ISSUE TITLE
OPENCOLLER NET VENDER  NO LONGER WORKING

### ISSUE THREAD

**Issue by delightfuldel** [OpenCollar/opencollar#63]

**Comment by delightfuldel** [comment]
I had several vendors set out in my shops and sim landing point. I checked  them today and see they are no longer active and I got a message that now i have to be a  registered distributer.  Is theRE a way i can do this.Thanks

**Comment by WendyStarfall** [comment]
We recently migrated our distribution network after finding a sponsor (CasperTech) and had the network distribute an "out of date" notice for approx. a month. Some vendors might not have updated tho and just went offline without ever giving the notification. Please get the new vendors, whitelisting manually is no longer necessary now! Links below ->

https://www.primbay.com/product.php?id=1787275
https://marketplace.secondlife.com/p/OpenCollar-Vendors/5496956
http://www.opencollar.at/2/post/2013/11/new-vendors-gift-options-and-3937.html

http://maps.secondlife.com/secondlife/Qandico/223/141/77
