### ISSUE TITLE
temporary owner persists after safewording

### ISSUE THREAD

**Issue by WendyStarfall** [OpenCollar/opencollar#636]
To reproduce:
1. have no owner or no vanilla setting
2. turn kidnap on (whether vulnerable or not doesn't matter)
3. let someone kidnap you
4. safeword

Outcome:

The setting gets cleared, however the temporary owner remains listed in auth and will of course keep access until auth resets. The unofficial reboot command can fix it for now. This is however no solution.

**Comment by GarvinTwine** [comment]
This happens due to a removal of a section in auth i didnt see necessary to have at all.
How ever one line change in kidnap fixes this.

**Comment by GarvinTwine** [comment]
fixed in #637
