### ISSUE TITLE
'Set Label' appends unwanted text to the front

### ISSUE THREAD

**Issue by GreyMars** [OpenCollar/opencollar#638]
When using Apps -> Label -> Set Label to set the label it always appends 'text' to the front of the label.  

Unable to test if it also happens for <prefix>labeltext <text> as that command is not working for me.  (potentially a second bug, or potentially user error.)

**Comment by GarvinTwine** [comment]
opsy... i forgot to remove the "text" command when using the TextBox to set the label, fixed in a bit

**Comment by GarvinTwine** [comment]
fixed in #639 for meshlabel label doesnt need fixing as i did not forget to change it there ;)
