### ISSUE TITLE
Somehow I lost permission to animate you

### ISSUE THREAD

**Issue by Attitum** [OpenCollar/opencollar#64]
1 start off with Basic collar
2 update using updater
3 reset collar
4 pick an animation i choose (kneel)

[23:33:35] OpenCollar: Error: Somehow I lost permission to animate you.  Try taking me off and re-attaching me.

Dont matter what animation you pick from that point thats all you get,  Sure reset collar again get same results.

**Comment by WendyStarfall** [comment]
we been getting this error at random since a long time now and still looking at it; sometimes if you get a fresh collar it would throw this error and as soon as you re-wear it the error never shows up again, I thought it was a missing reset but that wasn't it

re-wear the collar and it will never give the error again

**Comment by littlemousy** [comment]
I've noticed a few people mentioning this in the chatter group in-world.  I looked at the anim script, it only asks for permission to animate as it is attached.  There are some lines commented out suggesting that it used to ask permission to animate in the state_entry event, which used to be run each time the collar was rezzed courtesy of an llResetScript() in the on_rez event, also commented out.  There is a check for anim permission made several times in the script, in each instance, it displays the same "lost permission to animate you" text.  I would suggest adding the line:

if (llGetAttached()) llRequestPermissions(llGetOwner(),PERMISSION_TRIGGER_ANIMATION);

at each of these points.  This will not pop any permission dialog boxes for the wearer, as permission to animate is granted automatically for attachments.  The warning could also be changed to something like "Error: I lost permission to animate you, please try again."

It's not exactly a fix, more of a workaround. I can't for the life of me work out why a regular collar would ever not have permission to animate the wearer.  It is requested every time the collar is attached, and there are no other llRequestPermissions in the script to clobber it

As a side note, if the collar is attached as a temporary attachment, then the permission to animate seems to be dropped after the attach is complete.  The workaround suggested above would also make it possible to attach a collar using the llAttachToAvatarTemp() call, from a single drop-in script.  I can provide a sample if anyone thinks this would be of benefit to the community.

**Comment by WendyStarfall** [comment]
Yes, please drop me a sample in-world! The temp attachment idea is awesome, I read the discussion about it in the R&D the other day. For anim, I want to try what Medea suggested and re-arrange the order of the resets some but the fix you propose is something else I can try, thanks for that and if I put it in, I will attribute you in the commit unless you want to send me a pull request? =)
