### ISSUE TITLE
Pose cleared with Safeword Returns After Relog.

### ISSUE THREAD

**Issue by MystyBoots** [OpenCollar/opencollar#642]
Settings:  I am wearer and primary owner.  I set a pose to kneel (mykneel) and I kneel.

Actions:  I say "RED" in open chat and get the appropriate message that safeword was used and my kneel is cleared and I'm standing.

Problem:  If I logout and log back in, my avatar is kneeling again.  It seems the safeword only clears the pose for that SL session but the pose returns for subsequent sessions.

**Comment by GarvinTwine** [comment]
i could reproduce and confirm this.
I dont recall to have changed anything about this in the 4.0 development so this "feature" should be there for longer already. 
Lets fix this for 4.0

**Comment by GarvinTwine** [comment]
fixed in #643
