### ISSUE TITLE
No .settings Notecard

### ISSUE THREAD

**Issue by MystyBoots** [OpenCollar/opencollar#652]
Hi,
Under "Options" there's still a "Print" button which displays all the current settings and says, "Everything below this line can be copied & pasted into a notecard called ".settings" for backup:"  However the current version of the collar I have (OpenCollar BETA 4.0/3.6.3:) does not have a .Settings notecard.  Is it expected the user create one or?

**Comment by WendyStarfall** [comment]
Yes, the user can create the .settings card herself and keep it in her inventory for backup purposes.

In 4.0 versions it is not required to ship the collar with a .settings card pre-installed but can be done if the collar is supposed to already have custom settings out of the box.

**Comment by MystyBoots** [comment]
Ok, so if I make a .settings card and stick it in the 4.0 collar, it will read it and use it, but it's not needed.  Got it.

**Comment by XenHat** [comment]
Perhaps we can close this?

**Comment by MystyBoots** [comment]
Sure... although I'm not sure my comment about the collar using the card if there is accurate.
