### ISSUE TITLE
Spelling Boo Boo in Help Notecard

### ISSUE THREAD

**Issue by MystyBoots** [OpenCollar/opencollar#653]
Going to Help/About and then Help presents the .help notecard.  In a line that says, "Your collar also has a safeword which you simply type in the nearby chat. This will lift all RLV resctrictions, unpose and unleash you. It will also send your Owner a message to check for your well being. RED in capital letters is the default safeword."  The word resctrictions should be restrictions

**Comment by WendyStarfall** [comment]
Thanks, the typo has been correct in bda92be5b9ab92e72d503d9841881efd291cfd9c
