### ISSUE TITLE
Generic Comments

### ISSUE THREAD

**Issue by MystyBoots** [OpenCollar/opencollar#655]
Hi,

Just some generic feedback from Brandy (SFLand Inventor) and I.  The more specific items (pose cleaning, notecard boo boos, display comments, etc.) I’ve put in separate issue reports.

Overall, we love the direction the collar is going and the wonderful things you guys do for the SL community.  I can’t list everything we like here, but I want to point out a few highlights.  The Kidnap feature, the RLV Dazzle and Daze, and the Vanilla options are great.  We also love the safeword being an actual word and the IM going to the owner(s) if safeword was used.

As far as a few tweaks we’d like to see:  Well, it seems only 3 people for primary owner.  Could you bump this up to 5 maybe, pretty please?  Also, the Vanilla button is where the limit range used to be but we feel a limit range option should still be in the collar – if not under Access then maybe somewhere else?  And finally for this note, we’re not seeing a “get handle” or “get post” under Leash.  Will they be coming back?

Anyway, great stuff!!!  We’ll keep testing and commenting.

**Comment by WendyStarfall** [comment]
Hi and thanks for the feedback. Here are answers to some of your questions:

> Well, it seems only 3 people for primary owner. Could you bump this up to 5 maybe, pretty please?
- Three primary owners is the design for version 4.0. This has been the only request to increasing this number after several weeks of beta testing. It can be very easily modified on a case by case basis.

>  Also, the Vanilla button is where the limit range used to be but we feel a limit range option should still be in the collar – if not under Access then maybe somewhere else?
- The LimitRange button is not suited for a menu button. Region wide public access to the device as a menu button led to a lot of confusion and it is highly unusual that somebody desires intimate role play interaction over a greater range than max. **20 meters** which is already quite far. Users who wish to deactivate the range limit can still do so however by typing: `[prefix] limitrange off`

> And finally for this note, we’re not seeing a “get handle” or “get post” under Leash. Will they be coming back?
- These buttons were needlessly bloating the menu and will not be added in version 4.0. Once a Leash Holder or Post are acquired these buttons essentially become obsolete for your partners. At the moment these items can still be acquired via command line: `[prefix] give holder/post`

**Comment by MystyBoots** [comment]
Thank you for your comments to the above!!  I would like to comment on the "range"...  Me, Brandy, and a few others I know have experienced some really fun times being on a sim and all of the sudden being posed, stripped, RLV folder items added, and not seeing anyone near by... not knowing who is accessing your collar....  True, it's not for everyone, but for us it's a blast!!  So we were looking for the "unlimited range" option.

**Comment by WendyStarfall** [comment]
> Users who wish to deactivate the range limit can still do so however by typing: [prefix] limitrange off
