### ISSUE TITLE
Vanilla Button checks for trusted user but text says "Access Denied"

### ISSUE THREAD

**Issue by MystyBoots** [OpenCollar/opencollar#657]
Settings:  Person A is wearer and Not Owner, Vanilla Mode is Off, Kidnap is On, Vulnerable is off.

Actions:  Person B clicks collar and does a kidnap and Person A allows.  Person B then goes to Access and clicks Vanilla.

Problem:  When Person B clicks Vanilla the little box gets the X like it's now turned on, but the text message says "Access Denied."  Person B can click the Vanilla option several times turning the little X on and off, but it doesn't seem Vanilla mode is ever actually activated.

**Comment by WendyStarfall** [comment]
Thanks for reporting this bug. Thankfully this is mostly a cosmetic issue of erroneous checkbox behavior.

Kidnappers or "temporary owners" are not authorized to manipulate access lists. A kidnapper cannot add himself as Owner or Trusted and also cannot add other avatars to these lists and cannot enable vanilla.

**Comment by GarvinTwine** [comment]
fixed in  #658
