### ISSUE TITLE
Leash Configure Options

### ISSUE THREAD

**Issue by MystyBoots** [OpenCollar/opencollar#660]
Hi,

Under Leash >  Configure:  I'm not seeing any behavior differences when turning on or off the "Turn" and the "Strict" options.

I expected Turn to turn the leashed person to me, but walking around the leashed person behaves the same regardless of this setting.

I'm not sure what to expect with Strict.

**Comment by WendyStarfall** [comment]
The behavior of the leash can be noticed when leashed, led and played with, not when standing still.

I have tested Turn and found no problems, the feature turns the leashed character towards the leader.

Strict mode was released in April 2014. I expect users on release versions to read [the documentation](http://www.opencollar.at/leash.html) for such things. 4.0 pages are neither linked nor published yet but will be available at version release day.

**Comment by MystyBoots** [comment]
Well, I thought it might turn the leashed character, so I leashed Brandy and I walked all around her and she never turned or moved.  If I tug the leash she faces me, but she does that even with option off.  I'll do some more testing! :)

**Comment by WendyStarfall** [comment]
If you turn on RLV/a debug messages, you will notice that when Turn is enabled, your collar issues a rlv command `@setrot`. You will also want to turn your AO off to see your character indeed turn. Selected viewers have a very useful feature that will automatically turn the character when walking backwards.

![2015-08-10_0345](https://cloud.githubusercontent.com/assets/1100007/9158196/721aac34-3f12-11e5-88f2-ada14d215a01.png)

With this feature activated, the Turn option in the collar might look different. This option has been requested by a whole bunch of people who prefer to use 1st person view a lot. For them the ability to deactivate automatic leashed turning must be very important, even more so while wearing an oculus rift or similar device, I guess.
