### ISSUE TITLE
RLV Exceptions not applied when kidnapper is former owner

### ISSUE THREAD

**Issue by ml132** [OpenCollar/opencollar#664]
To reproduce:
1. Add someone else as an owner.
2. Have them remove themselves (or runaway)
3. Enable kidnapping
4. Have the same person kidnap you 

This might be related to #663.
Re-rezzing the collar fixes this issue

**Comment by GarvinTwine** [comment]
not related to 663 but fixed in #668 though this played scenario makes absolutely no sense to actually happen this should still always work.
