### ISSUE TITLE
Some thoughts about NOTIFY, NOTIFY_OWNERS, SAY, POPUP_HELP 

### ISSUE THREAD

**Issue by ghost** [OpenCollar/opencollar#690]
Like llMessageLinked(LINK_DIALOG, DIALOG, ....)  these 'messages' frequent have large texts.
llMessageLinked(LINK_ROOT, NOTIFY, {large text}, kID)  send message to all scripts in root prim, but only 'oc_com' is receiver!
all other scripts have to process these unwanted messages.

it may be better to transfer these functions (NOTIFY, NOTIFY_OWNERS, SAY, POPUP_HELP ) to the oc_dialog script?

p.s. excuse my bad english

**Comment by GarvinTwine** [comment]
If you look at the other scripts, they have first if in the link_message event:
if (iNum == NOTIFY || iNum == SAY) return;

**Comment by ghost** [comment]
Yes, but event happens, and react scripts. all scripts.
This renders meaningless place scripts in different links

**Comment by GarvinTwine** [comment]
i will try this :)

**Comment by ghost** [comment]
I'm trying to do it

**Comment by GarvinTwine** [comment]
wait... we think about to move com into a own prim for that

**Comment by ghost** [comment]
oc_com must be at the root prim for proper communication with other devices!
it use root prim uuid

**Comment by GarvinTwine** [comment]
i just fear dialog is anyway the most busy script and every llDialog has already a forced delay (sleep) of 1.0 seconds. If now a NOTIFY_OWNERS sends llInstantMessage to not near owners, the script is sleeping quite a bit

**Comment by WendyStarfall** [comment]
Yes, the pause after IM worries me too. Let's see how well it does in practice.

**Comment by ghost** [comment]
oc_com is anyway the most busy script too!

it may be better to make a separate script for NOTIFY - SAY etc?
and let him sleep as he wants

**Comment by GarvinTwine** [comment]
for performance and all would be optimal to make a own dedicated and in its own prim located NOTIFY script ;) but we all know how important script count these days is...

**Comment by ghost** [comment]
I think that we can close this debate?
