### ISSUE TITLE
After removing the Bell with chat command we get a re-menu to Bell

### ISSUE THREAD

**Issue by WendyStarfall** [OpenCollar/opencollar#747]
Versions: 4.0.0 to 4.0.7

The plugin is correctly removed but we end up back in a "dead" Bell menu.

Zi Ree reported this bug. Thanks!

**Comment by GarvinTwine** [comment]
This is a real mystery... how does the script manage to call a menu function after it has been deleted?
Anyway, i will add a return; **after** the deletion to make sure there wont be a menu popping up.

**Comment by GarvinTwine** [comment]
fixed in #748
