### ISSUE TITLE
a simple method to test the link-set's build integrity

### ISSUE THREAD

**Issue by WendyStarfall** [OpenCollar/opencollar#750]
Versions: 4.0.0 to 4.0.11

I've been closely observing others efforts to build the new 4.0 API and I'm happy to have learned that some users figured it out just by digging some through the PRs since mid July or fully on their own.

However, we should add a few basic helpers to prevent mistakes. Zi Ree suggested that link specific scripts could test if they were indeed in the right link. I think this is a good idea and should be considered.

The most obvious build mistake would be falsely linked `com [root]` and `auth [2]` then nothing will work at all. It's also not hard to test `dialog [3]` because if not getting any menus something obviously went wrong. Things get icky though with `RLV [4]` and especially with `settings [5]` as the latter may not be noticed until a user already further downstream realizes RLV is gone or that nothing is ever stored.

I propose we add a simple test if the script is in the correct link and play a sound and OwnerSay if not. :speak_no_evil:

**Comment by WendyStarfall** [comment]
How about adding a `LINK_ALL_OTHERS` command in `com [root]` that would call a test in all Core5.
- `we test integrity`

That way we would avoid spamming as soon as the script had been dropped into a prim.

PS: It's a builder's responsibility to test integrity before starting to deploy their kit and adding this is already more than you would get with most other things. This should add plenty of convenience. :cake:

**Comment by GarvinTwine** [comment]
OK, i made something here which needs adjustments in all corresponding scripts of course:
the command would be as suggested and this would be the output:
`Otto: ga test integrity`
`OpenCollar 4.0: Starting Core5Scripts integrity test...`
`OpenCollar 4.0:`

`Integrity Test Passed!`

or if something is not right:

`Integrity Test Failed:`

`oc_anim not found!`
`oc_couples not found!`
`LinkedPrim Nr. 2 - oc_auth     (correct)`
`LinkedPrim Nr. 5 - oc_settings     (correct)`
`LinkedPrim Nr. 3 - oc_dialog     (correct)`
`LinkedPrim Nr. 4 - oc_rlvsys     (correct)`

or

`Integrity Test Failed:`

`oc_anim not found!`
`oc_couples not found!`
`LinkedPrim Nr. 3 - oc_auth     (WRONG)`
`LinkedPrim Nr. 6 - oc_settings     (WRONG)`
`LinkedPrim Nr. 4 - oc_dialog     (WRONG)`
`LinkedPrim Nr. 5 - oc_rlvsys     (WRONG)`

or 

`Integrity Test Failed:`

`LinkedPrim Nr. 6 - oc_auth     (WRONG)`
`LinkedPrim Nr. 3 - oc_settings     (WRONG)`
`LinkedPrim Nr. 2 - oc_couples     (WRONG)`
`LinkedPrim Nr. 2 - oc_anim     (WRONG)`
`LinkedPrim Nr. 5 - oc_dialog     (WRONG)`
`LinkedPrim Nr. 4 - oc_rlvsys     (correct)`

**Comment by WendyStarfall** [comment]
I changed the command to `<prefix> verify` which should make more sense.

**OFF-TOPIC**

Patching some collars went well, unfortunately my personal device had the same problem old Owner Huds and Tech Collars had:

![aa098ff3e041d614e2d2aa7a232d6f23](https://cloud.githubusercontent.com/assets/1100007/11171000/88558f54-8be4-11e5-9797-3ab6220f7a6a.png)

For no reason at all a script shows up called `Old Script` that appears to be an older variation of one of the existing scripts, effectively duplicating a script. This time it was `oc_rlvsys`.

The Installer removes `Old Script` by default with the `DEPRECATED` bundle, so that means `Old Script` shows up after the installation procedure is long over.

`Old Script` cannot be opened or read but you can figure it out which it is by finding the duplicated menu with trial and error. When trying to open the file itself it will say "script missing from database" even though it is obviously running.

PS: This is about as demotivating as things can get. We have no influence on that at all and an otherwise fully flawless device can break because of _bad luck_. I'm not sure how to approach this except in very primitive ways where the user is expected to remove the running, yet non-existent, `Old Script` manually.
