### ISSUE TITLE
oc_dialog: Stack-Heap Collision, Script run-time error

### ISSUE THREAD

**Issue by ghost** [OpenCollar/opencollar#757]
It happens after several (5-6) consecutive Force Sits
I guess a bug in the Sensor Dialog

**Comment by WendyStarfall** [comment]
I have been able to reproduce this on `4.0.14`

> [10:20] Wendy Starfall: we sit
> [10:21] Wendy's Collar: Sit down, and stay there!
> [10:21] Wendy Starfall: we sit
> [10:21] Wendy's Collar: Sit down, and stay there!
> [10:21] Wendy Starfall: we sit
> [10:21] Wendy's Collar: Sit down, and stay there!
> [10:21] Wendy Starfall: we sit
> [10:21] Wendy's Collar: Sit down, and stay there!
> [10:21] Wendy Starfall: we sit
> [10:21] Wendy's Collar: Sit down, and stay there!
> [10:21] Wendy Starfall: we sit
> [10:21] Wendy's Collar: Wendy's Collar [script:oc_dialog] Script run-time error
> [10:21] Wendy's Collar: Stack-Heap Collision
