### ISSUE TITLE
.settings or defaultsettings

### ISSUE THREAD

**Issue by Attitum** [OpenCollar/opencollar#768]
Paragraph below is making a reference to default settings but i think now its .settings

For custom defaultsettings, the most ever simple way to proceed would be taking a collar, wiping it fully clear of any settings with a cold boot (or just grabbing a free, fresh one from the vendor) and setting everything you wish as the default behaviour. Set your owner, your preferred relay mode, hardwire the core or individual locks and dump the settings cache. Then, copy the print and paste it into the defaultsettings notecard. 

Issues found - non of this actually works at all, tried .settings tried defaultsettings

tested on > Ruffneck Collar (4.0.18)

RLVSYS=on~1
GLOBAL=DeviceName~Ruffneck Collar~locked~1
PARTICLE=C_Texture~Chain~ParticleMode~Classic~Gravity~-1.1~Size~<0.13,0.13,1>~R_Texture~Leather
ANIM=PoselockRank~500~animlock~1~TweakPoseAO~1~PoseMoveWalk~~walk_Crawl~PoseMoveRun~~run_Crawl~currentpose~kneel,500
CAPTURE=capture~1~risky~1
LEASH=leashlength~2~strict~1,500
RESTRICTIONS=send~500~rummage~500~read~500~touch~500~dress~500~hear~500~stray~500~dazed~500
AUTH=public~1
TITLER=title~Property~on~1~auth~500~height~1.000000

**Comment by WendyStarfall** [comment]
This page on the manual is still referring to OpenCollar 3.9 and will be updated eventually.

**Comment by Attitum** [comment]
And what about this part lol the actual problem

Issues found - non of this actually works at all, tried .settings tried defaultsettings

tested on > Ruffneck Collar (4.0.18)

RLVSYS=on~1
GLOBAL=DeviceName~Ruffneck Collar~locked~1
PARTICLE=C_Texture~Chain~ParticleMode~Classic~Gravity~-1.1~Size~<0.13,0.13,1>~R_Texture~Leather
ANIM=PoselockRank~500~animlock~1~TweakPoseAO~1~PoseMoveWalkwalk_Crawl~PoseMoveRunrun_Crawl~currentpose~kneel,500
CAPTURE=capture~1~risky~1
LEASH=leashlength~2~strict~1,500
RESTRICTIONS=send~500~rummage~500~read~500~touch~500~dress~500~hear~500~stray~500~dazed~500
AUTH=public~1
TITLER=title~Property~on~1~auth~500~height~1.000000

**Comment by WendyStarfall** [comment]
The settings print says:

> Everything below this line can be copied & pasted into a notecard called ".settings" for backup:
> 
> GLOBAL=DeviceName~OpenCollar
> RLVSYS=on~1
> etc.

The documentation for this part of the collar will be published eventually. There is no reason to use the settings card as long as the OpenCollar 4.0 is in its pre-release phase. If you have an actual use case for the card, please make it but don't quote the manual section or duplicate the issue.

Settings are stored in the collar correctly and work just fine.
