### ISSUE TITLE
.settings

### ISSUE THREAD

**Issue by Attitum** [OpenCollar/opencollar#769]
tested on > Ruffneck Collar (4.0.18)

Issues found - non of this actually works at all, tried .settings

RLVSYS=on~1
GLOBAL=DeviceName~Ruffneck Collar~locked~1
PARTICLE=C_Texture~Chain~ParticleMode~Classic~Gravity~-1.1~Size~<0.13,0.13,1>~R_Texture~Leather
ANIM=PoselockRank~500~animlock~1~TweakPoseAO~1~PoseMoveWalkwalk_Crawl~PoseMoveRunrun_Crawl~currentpose~kneel,500
CAPTURE=capture~1~risky~1
LEASH=leashlength~2~strict~1,500
RESTRICTIONS=send~500~rummage~500~read~500~touch~500~dress~500~hear~500~stray~500~dazed~500
AUTH=public~1
TITLER=title~Property~on~1~auth~500~height~1.000000

**Comment by WendyStarfall** [comment]
Duplicates #768
