### ISSUE TITLE
> Main Menu > Animation

### ISSUE THREAD

**Issue by Attitum** [OpenCollar/opencollar#77]
Take Basic Collar
Goto Animation button
Select AnimLock

> Observe Double Dialogue Menu

**Comment by ghost** [comment]
OpenCollar - anim:

in function:
410   integer UserCommand(integer iNum, string sStr, key kID)
.......
494         AnimMenu(kID, iNum);  <<<<< need remove, just rem it: //AnimMenu(kID, iNum);
