### ISSUE TITLE
Beta Branch: RLV Login Notification

### ISSUE THREAD

**Issue by WendyStarfall** [OpenCollar/opencollar#8]
Currently neither wearers nor owners get any RLV notification if logging on with RLV disabled in the viewer. Things would happen here -> https://github.com/OpenCollar/OpenCollarUpdater/blob/beta/LSL/OpenCollar%20-%20rlvmain.lsl#L558

However, is it necessary to have this notification at all? Usage case would be that a wearer logs on with RLV disabled and cold boots the collar to rid of the owner and restrictions. It's a moral question if that's an "OK" thing to do. Sort of cheating or dodging the notification that would already be there when using runaway or the safeword. I vote for getting rid of this notification all together, it causes more drama in everyday use than it would actually be used by extra-geeky subs to cheat in hope to get scolded. A person can only be controlled so far in my opinion and we shouldn't add fuel to drama prone stuff. What happens with the notification is hinting the sub attempted maybe a break of trust and consent; that will in most cases always come across wrong.

That's a Yay for ridding of it all together and a Nay for fixing and keeping it. Just comment with either, please.

Yay.

**Comment by NorthGlenwalker** [comment]
Yay, as subs do login from phones which are not alays rlv enabled anyway

**Comment by ibrew** [comment]
Nay, fix and keep. It's the current expected action and some people like it. It's also trivial to disable should a user wish to not give such notification. I recommend against making changes to the user's collar experience and work on fixing bugs. My understanding is that 4.0 is where the new stuff should go.

**Comment by WendyStarfall** [comment]
Looks like the notifications DO happen on 3.923 and owners get notified only if a restriction was set, this is all working just fine. Medea did the debugging.
