### ISSUE TITLE
AO misses handshake after relog

### ISSUE THREAD

**Issue by WendyStarfall** [OpenCollar/opencollar#819]
On the developer version of the `OpenCollar AO 160120.4` once we relogged, the AO won't perform the handshake with the collar. Re-wearing the AO does the handshake.

**Comment by GarvinTwine** [comment]
Couldnt reproduce this yet but i actually wonder if this ping-pong play between collar and ao is necessary anyway.
I removed the messages for "Open Collar detected/not detected" but else nothing changed, it makes no difference for the AO or Collar if either is present. They try to interact with each other anyway just some menu buttons dont work if one is missing. The only little benefit this has that the AO does narrow its listener to the collar's UUID on a anyway avatar specific created channel on a avatar specific send message by llRegionSayTo... not sure if this really justifies a 10 or 20 second timer loop of messages.

**Comment by WendyStarfall** [comment]
I can reproduce it every time. When I'm missing the handshake, I won't be able to call the AO menu from the collar's Animation menu.

Steps:
1. Wear AO
2. Check handshake `<prefix> ao menu`
3. We get the AO Menu
4. Relog
5. Check handshake `<prefix> ao menu`
6. We don't get anything

I've tested this as wearer and remotely as owner. Behaviour is exactly the same. We are missing something or we use different scripts! lol

**Comment by WendyStarfall** [comment]
After testing it for another hour, I'm still able to reproduce it every, single time.

The AO Menu call from the collar's Animations menu and the collar command will fail after relog and no GUI buttons indicate off and on states when the collar is pausing the AO.

Pausing appears to work correctly but the menu call does not and that defeats the primary purpose of using the whole OpenCollar AO over `oc_accessory_aolink`.

Something happens when we attach it, that doesn't correctly happen when we relog.

I doubt the ping/pong method is necessary to perform simple things like indicating button states or making menu calls work in between devices. If that is still required, then it is even in performance with the previous AO in that aspect, which is totally ok but if it doesn't work at all means we can't ship it tomorrow.
