### ISSUE TITLE
Remote jumps off visible screen

### ISSUE THREAD

**Issue by WendyStarfall** [OpenCollar/opencollar#820]
The developer version of the `OpenCollar Remote 6.0.0/150120.4` bops off the visible screen on first attach and re-attach.

**Comment by ghost** [comment]
look at oc_remote_leashpost script inside OpenCollar Remote
what is it there?
this stript moves HUD off the screen.
I believe it should be inside Leash Post.

I remove it and bug gone.

**Comment by WendyStarfall** [comment]
Oops! I accidentally dropped it in there when assembling. LOL :speak_no_evil: 

False alarm then, I'd say we are golden with this HUD, some more tests tomorrow. :see_no_evil:
