### ISSUE TITLE
Issue with Exceptions not working after relog

### ISSUE THREAD

**Issue by michealmmeyers** [OpenCollar/opencollar#847]
My girl uses OC script 4.0.16 in her collar.  If I block her IMs and receiving IMs, the exception works.  But if she relogs with the restrictions still in place then the exceptions will not work for myself as owner and the people that are on her trusted list.

**Comment by GarvinTwine** [comment]
What do you mean by "the exception will not work" exactly?
They do not get set in the rl-viewer? (this would be a collar issue)
or
They get set but do not work? (this would be a viewer issue the collar cant do nothing about)

I didnt have a 4.016 collar handy, you might to install the latest patch to 4.2 and recheck again:

I just tried it and after relog the restrictions as well as the exceptions for owners and trusted were in place. And IMs worked fine between owner and collar wearer.

**Comment by michealmmeyers** [comment]
Okay, so here is the order of events.

I take my girl and shut down her IMs, sending and receiving.

For some reason she has to relog her avi, she uses Firestorm build 47975 w/RLVa enabled.

Upon return she is not able to receive IMs from me or anyone on her Trusted list.

When I go into the collar, it shows that the Exceptions for Owner and Trusted are in place.

When I go into Restrictions it shows that she isn't able to receive or send IMs.

Hopefully that clears up the confusion a bit.

**Comment by GarvinTwine** [comment]
Not really. I tried to reproduce this event, using the same viewer, but a recent OpenCollar version, which is 4.2 (which you should always do before reporting an issue as it might be fixed already).
In Exceptions to be an effective exception, something has to be chosen, which is ALL by default for owner and all but Lure and RefuseTp for trusted. 
Now the question is, are these exceptions in place in the viewer... in Firestorm you can see that when you open the Restrictions menu under RLVa and switch to the Exceptions tab.
But please use first the 4.2 and try again, before time on something already fixed is spent here. 
Thanks

**Comment by WendyStarfall** [comment]
Couldn't break it myself. This is superseded by 4.2.x or needs more info about the build model.

Re-open if necessary.

**Comment by WendyStarfall** [comment]
One more idea if the OP is still following.

Summer 2015 a bug with ghosting and randomly dropping attachments resurfaced on SL and was, supposedly, addressed in "Project BigBird". The problems are mostly these two issues:
- [MAINT-4351 HUDs and attachments intermittently and randomly detach after teleports, sometimes reattaching on their own shortly after, sometimes staying detached completely, or showing as "worn on Invalid Attachment Point" while still detached ](https://jira.secondlife.com/browse/MAINT-5278)
- [MAINT-5278 [Project BigBird] Attachments From Inventory Fail Silently ](https://jira.secondlife.com/browse/MAINT-4351)

(I don't know why these areas in the JIRA sometimes give "Permission Violation" when trying to access.)

In such a case you, yourself see the collar as worn. You might even get a menu normally but it is no longer properly handled by the viewer and you have exceptions and restrictions missing even though you see them just fine as RLV debug print. Then once you relog a second time, the item is fully detached, usually along with a bunch other attachments.

To try working against this:
- Make sure your viewer is the recent release of whatever brand you use.
- Avoid adding multiple items to the same attachment spot.
- Avoid wearing multiple items all at once, like right-clicking a directory and "adding" it.

PS: I keep my personal collar in #RLV/.outfits/.core and never have this issue but I have it every once in a while with my mesh body hud that attaches with every outfit and with my right mesh hand.
