### ISSUE TITLE
Transmuter

### ISSUE THREAD

**Issue by Ariallynn** [OpenCollar/opencollar#881]
While keeping up with the updaters and such and using my own collars to test the new system on I found an error in the transmuter that does not seem to happen regularly. 
The update will take, but some of the menu buttons (random which ones) have been known to break and not work. For me it was the leash configure. A reboot and fix was done as well as a full reset to a 3.9xx version and an attempt to re-update. The same menus broke on the second try. Others have had different pieces of the collar break on transmutation of which I learned they fixed by stripping out the scripts in the updater, making there own prims and then linking them.

**Comment by WendyStarfall** [comment]
Thanks for your report. Some more information would be extremely useful:
- What were the names of the collars showing the erroneous behaviour?
- What permissions did they show while still in the inventory?
- What permissions did they show on the object once rezzed on the ground?
- Are samples of these collars available somewhere?
- What versions did they originally have?
- Was the Transmuter the 6.0.0 or the 6.1.0 variation?

**Comment by Ariallynn** [comment]
Kibitz Harvest Metal Collar Onyx (scripted)
Inventory: Permissions, no transfer, mod,copy
Ground: No Transfer, Mod, Copy
Kibitz sells this collar inworld
Version 3.997
The transmuter was 6.0

**Comment by WendyStarfall** [comment]
The issue with "leash configure" makes no sense. This has nothing to do with the transmutation itself and cannot be related. I'm also not sure about the part where you mention that "menu buttons have been known to break". We had thousands of successfully performed transmutations meanwhile and got great feedback on it. What you described there sounds a lot more like a failed, manual assembly where scripts (i.e. particle) have simply been left out. I don't want to **buy** a collar from this party to do further tests. 💀

PS: All content I found from the mentioned party was "no copy" gacha stuff that was being resold on MP.

**Comment by Ariallynn** [comment]
I bought the collar at her inworld store. There it is copy, mod, no
transfer. I figured it would be a hard to replicate issue. As for the menu
button, when i did the update that was what failed. Pressing the configure
button under the leash menu produced no extra menus.
