### ISSUE TITLE
System: Origin and distributor.

### ISSUE THREAD

**Issue by WendyStarfall** [OpenCollar/opencollar#889]
**Version:** `6.1.2 (160315.100000)`

With the `.distributor` card we explored ways to link back to the origin of the particular device. In some cases, like default OpenCollar, the device can also be freely transferred once the card has been removed with `[prefix] jailbreak`. We want to be able to automatically adjust this origin to the new distributor. In motion we adapt the "jailbreak logic" to more of an "official seal" that is given to avatars who have been recognized as important contributors to OpenCollar. Instead of "jailbreak" we use `[prefix] rm seal`.

**Example:** Tom acquires an OpenCollar from an official source like Virtual Disgrace™. He made some modifications to it, like defaulting himself to the Trust list and now wants to share it with his friend. In order to do that, he first has to remove the "official seal" with `to rm seal` so he can pass it on. On the modified device his friend correctly sees `Origin: Tom` in info and version prints and in the Help/About menu.

**Note:** Users need to be able to contact the person who passed the device on, especially if full permission resource had been used and if modifications were made. Often the object's creator is erroneously contacted for assistance who then has no way to know which modifications were made and can't help.

**Comment by GarvinTwine** [comment]
**Note:** After transmutations we set the origin to "Unknown" as for these collars the test have shown that in most (if not all) cases the current collar owner will be shown, which means it is not possible to determine in these cases the real distributor so we say "Unknown"
