### ISSUE TITLE
Beta Branch: Parsing defaultsettings on demand

### ISSUE THREAD

**Issue by WendyStarfall** [OpenCollar/opencollar#9]
I think we eventually should add a little feature to the Setting menu that would parse a defaultsettings card on clicky. Imagine it like this:
1. wearer/owner creates a custom defaultsettings card
2. plays with stuff, changes cosmetic things and what not
3. wants it all back how it was stored in the card
4. goes to help/debug -> setting and clicks a "Reset" or some such button

Also should we have a llTextBox for users to be able doing defaultsettings copypasta? This would make it possible for people to backup their settings anywhere, a notecard in the inventory, a text or doc file on their computer.. and then just paste them in the textbox to load them up.

**Comment by ghost** [comment]
this also helps the owner. he can add settings by remote

**Comment by ghost** [comment]
Reset to Default button is much appreciated!

**Comment by JoyStipe** [comment]
good luck, I've been wishing it were possible in SL to edit/create notecards inside objects for a long while. I doubt that Nan would've written the original settings script with anything less, and know I wouldn't have pubbed any released edits without that feature if it were possible.

**Comment by WendyStarfall** [comment]
aack I meant to say the /person/ creates it, not the program LOL

**Comment by WendyStarfall** [comment]
Looks like we can scrap the idea on using llTextBox for pasting settings ->

_"The textbox input is limited to 250 bytes (characters)."_

and to be honest... if somebody wants their settings parsed, it's as simple as relogging or taking the gadget on/off; in our current system it's even about backups or designer failsaves; we can come up with new ideas for 4.0
