### ISSUE TITLE
Leashing to wearers post

### ISSUE THREAD

**Issue by masterofsorts** [OpenCollar/opencollar#927]
When leashing using the rez post command, the wearer should have edit=n set in RLV to prevent unleashing by de-rezzing the post

**Comment by WendyStarfall** [comment]
The device no longer rezzes posts.

Play partners can rez their own post and hitch a leash to it with the `anchor` command. A restriction `@edit=n` can be set with the `forbid rummage` command but would only make sense if this wearer can _edit, delete or take_ their play partner's objects.

[Sample posts](https://github.com/OpenCollar/opencollar/blob/master/LICENSE#L165-L170) are included with boxed OpenCollar Orignials and embedded in the README/EULA card.

If you are interested in applying various RLV restrictions when casting a leash, you should check out "strict leashing" mode. This and other features in OpenCollar Six leashes are described [here](http://www.opencollar.at/leash.html).

EDIT: I completely forgot to mention here that the OpenCollar Remote device rezzes posts now. :speak_no_evil:
