### ISSUE TITLE
Loading settings from url requires a content-type header

### ISSUE THREAD

**Issue by natalja92** [OpenCollar/opencollar#946]
Hi,

i had issues laoding settings from an url...  i always run into

```
OpenCollar: Fetching settings from https://velvetclaw.org/noobs/11
OpenCollar: Empty site provided to load settings.
```

it figured out nginx didn't sent out content-type headers, as it does per default on extensions, not on the real cotnent type...

```
curl -v http://velvetclaw.org/noobs/11
*   Trying 176.9.135.58...
* Connected to velvetclaw.org (176.9.135.58) port 80 (#0)
> GET /noobs/11 HTTP/1.1
> Host: velvetclaw.org
> User-Agent: curl/7.49.1
> Accept: */*
> 
< HTTP/1.1 200 OK
< Server: nginx/1.10.1
< Date: Sat, 09 Jul 2016 13:29:09 GMT
< Content-Length: 170
< Connection: keep-alive
< Last-Modified: Sat, 09 Jul 2016 13:02:11 GMT
< ETag: "aa-537338708d4e0"
< Accept-Ranges: bytes
< 
BAL=DeviceName~OpenCollar~locked~1
RLVSYS=on~1
AUTH=owner~190e57d5-3112-46b4-8783-32ef6eab58d7
LEASH=leashlength~1~leashedto~36dcd165-e68d-d789-6a37-1e0e529cf078,503,0,0
* Connection #0 to host velvetclaw.org left intact
```

as i moved the file to a .txt extension, the collar loaded the settings from url...

```
curl -v http://velvetclaw.org/noobs/11.txt
*   Trying 176.9.135.58...
* Connected to velvetclaw.org (176.9.135.58) port 80 (#0)
> GET /noobs/11.txt HTTP/1.1
> Host: velvetclaw.org
> User-Agent: curl/7.49.1
> Accept: */*
> 
< HTTP/1.1 200 OK
< Server: nginx/1.10.1
< Date: Sat, 09 Jul 2016 13:29:13 GMT
< Content-Type: text/plain
< Content-Length: 170
< Connection: keep-alive
< Last-Modified: Sat, 09 Jul 2016 13:27:20 GMT
< ETag: "aa-53733e0f362e0"
< Accept-Ranges: bytes
< Vary: Accept-Encoding
< 
BAL=DeviceName~OpenCollar~locked~1
RLVSYS=on~1
AUTH=owner~190e57d5-3112-46b4-8783-32ef6eab58d7
LEASH=leashlength~1~leashedto~36dcd165-e68d-d789-6a37-1e0e529cf078,503,0,0
* Connection #0 to host velvetclaw.org left intact
```

Please mention that in the docs, as i don't think it's an open collar vault, but would help people who want to do preseeds :)

**Comment by GarvinTwine** [comment]
The issue is your website and nothing else here. 
The script simply doesn't get any data from that website if the content type is not specified.
If you use websites like pastebin.com or alike they do it all fine, I do not think a blog website is meant for such things at all.
So I think if people need to make things special like you, they will find out what an issue is, but normal users would rather get drawn back about too technical information they dont understand.

> Oz Linden added a comment - 01/Sep/15 8:27 AM
> 
> The problem is that the server is not returning a Content-Type header. LSL will only accept specified content types, and does not make any assumptions about the content type in the absence of an explicit header. 

from here: https://jira.secondlife.com/browse/BUG-9922
