### ISSUE TITLE
using leashto with an object key prompts the object's owner for permission

### ISSUE THREAD

**Issue by marrmist** [OpenCollar/opencollar#979]
What I did:
`<petprefix>leashto <leashpost's uuid>`

What happened:
I got an IM from the sim owner asking why I'm trying to leash a pet to her o_o

Expected results:
Either do nothing, or silently carry out the behavior of anchor instead of leashto.  (I prefer the latter)

Me editorializing:
Perhaps leashto and anchor should just be aliases for the same thing.

I will tackle this in the coming days and submit a PR myself, unless someone else particularly wants to do it themselves.  If I take on the work, I will start by looking for a clean way to unify the anchor and leashto commands, unless someone says I shouldn't.

**Comment by stawberri** [comment]
It appears that if you do this and the owner of the object accepts the prompt, you actually get leashed to the owner of the object, rather than the object itself.

**Comment by marrmist** [comment]
Ok thanks for noticing that detail.  And wow.  It looks like you already fixed it.  Thanks!

**Comment by GarvinTwine** [comment]
`leashto` is actually a deprecated command and nowhere mentioned in any OpenCollar Six help or documentation.
The expected result should be "do nothing".

Somehow it remained as alternative to `pass` (not to `anchor`) in the code.

Using the command:
`<petprefix>leashto <leashpost's uuid>`
Looks to me like a script is issuing the command as it is quite complex to get some foreign object's uuid without scripting to use in a chat command. 
So the right solution for this issue is to use the right command here which would be:
`<petprefix> anchor <leashpost's uuid>`
And if the script needs also leash to an avatar, check your target ahead and use `pass` instead.

The leash script is already overloaded with checks, who, what , where to, where from etc...
There is no need to have a command that does what two dedicated commands for object and avatars already do just because it has been there in a previous version.

Lets go by the KIS (Keep It Simple) rule and remove the undocumented command `leashto` as it only does the same thing another (documented) command `pass` already does and causes confusion as legacy command before we added the confirmation dialogue.

**Comment by marrmist** [comment]
Interesting history lesson.  Though I can't think of any circumstance where someone would actually want any leash command to have different behavior.  I think the best way to follow KISS principles is to make all these commands (including legacy ones, to minimize user confusion) alias to the exact same functionality.  That way there's no duplicate code and no possibility to use the wrong command.

To clarify, I also don't want a separate command that pulls double duty that's redundant with two other commands.  That would be silly.  (I just misunderstood the history behind these commands and what's currently in place).  I am wondering why not unify all three?  I'll let you consider it when I submit a PR, the result should make the code simpler and more maintainable overall.

**Comment by GarvinTwine** [comment]
Thanks for your thoughts.
The different behaviour of the commands lays in the target here, either it is an Avatar or an Object which results in two different types of scans (and texts) for the SensorDialog.
So two different commands are needed in case no direct uuid is given, which is the normal usage of these commands.
Giving a uuid is rather an exception, done by scripts, so not user but developer related. 

I will review and see to wrap things up a bit to avoid duplicate code, so again thanks to point this out.
Only `pass` and `anchor` will be valid commands, as previous explained no other is documented and in about one year nobody mentioned anything about a `leashto` command.

For users less commands mean less confusion, a command to pass a leash to another avatar and to anchor the leash to an object are totally clear in their functionality and any further command that suddenly does both but only if you do it with uuid is exactly what would confuse the user.

**Comment by marrmist** [comment]
I forgot to point out a minor misconception.  I did the command in question manually, not from a script.  It is actually very easy to manually get an object's uuid (right click, edit, copy keys) and it's useful if there are multiple objects in range with the same name.

Anyways, you make a good point about when these commands are used with a name instead of a key.  In that case I would suggest only unifying the code for how the commands behave when given a key.  Right now, leashing to object by key and leashing to avatar by key are separate pieces of code.  Unifying those two cases necessarily means simpler code (as Puddi demonstrated, distinguishing an object and avatar key is dead simple).

If leashto can remain a simple alias to pass, that seems like a good solution.  Since it's not documented, it can't possibly confuse users.  Only people who try to use it would notice it, and those veteran OC users would be more confused by its removal.  Is there any overhead from a command alias?

Ultimately, you are claiming that end users never use keys, and yet also claiming that unifying the behavior would confuse them.  How is it possible that functionality they would never access would confuse them?  This seems like a contradiction.

As I mentioned in group chat, this comes down to principle of least surprise: if someone issues a leash command with a key, whether object or avatar, I consider it fairly obvious what they intend.

To wrap up, I don't have a huge problem with removing the deprecated command, but I definitely don't see the merits of any arguments for doing so, and it seems punitive against long-time OC users working off of memory.  The most important part is that an object key should never result in prompting or leashing to an avatar (or vice versa).  I would definitely prefer, for the comfort of old time users, to keep the alias, and I also prefer for code cleanliness to unify functionality when there's no possibility for unwanted results (as with unique keys).

And my offer is open to work on this myself though I will hold off if you're saying you want to make the code changes.  Let me know!  And thanks for the quick responses and discussion!

**Comment by marrmist** [comment]
Ok after discussion on group chat, I realized I misunderstood Otto, and we do agree about unifying the functionality of leash commands when passed a key.  Sorry for continuing to comment.  All is well!

**Comment by GarvinTwine** [comment]
Wrapped up commands into one if statement.
`pass` and `anchor` will act as followed:
`prefix anchor` brings up the SensorDialog for objects to anchor the leash to
`prefix pass` brings up the SensorDialog for Avatars to pass the leash to
`prefix pass uuid` and `prefix anchor uuid` will both be redundant, the same commands actually, depending if the uuid is an avatar or not the confirm dialog will be send first or the leashing happens dierctly to the object. (this is actually the same as if someone clicked a target on one of the dialogues)
#981

**Comment by WendyStarfall** [comment]
Please have a PR already in place in case you want to propose these kind of edits in the future @marrmist.

There appears to be a lot of discussion for something that's apparently micro-optimization with result that it breaks the `pass` and `anchor` logic that was rock solid where nobody had any issues to "maintain" it.

Code maintainability is relevant to maintainers of code, like @GarvinTwine and I. My idea to leave certain legacy methods in place were not to please so-called "veteran OC users" but to give plugin and addon makers a few more month time to get their kit up to speed. No offense but as a "veteran maintainer" I can tell you though that it's time to get rid of cruft when somebody comes along with exotic use cases like these.

Separating the passing and anchoring was also my idea as the `leashto` scenario was mostly confusing users. We pass a leash to an avatar but we anchor or tie a leash to an object. This is easy to understand.
