### ISSUE TITLE
Safeword!

### ISSUE THREAD

**Issue by KarinKorpov** [OpenCollar/opencollar#991]
This isn't honestly.. when i do /1kkRED get my owner a message from the collar about my relay... but when i press "SAFEWORD" in kkrelay, can i cheat out without a message to my owner!

**Comment by WendyStarfall** [comment]
Hello Karin. No offense but it appears that you are mistaking the 'Issues' with some kind of support portal.

This is a collaborative workspace for contributors to the OpenCollar device. Issues are used to describe problems that can be solved with fixes or enhancements and are relevant to the functionality of the many various plugins in the device. Addressing user's individual preferences estranges the purpose of 'Issues'.

Whether you want your `SAFEWORD` button disabled or not has to be addressed in between authorized owners on your device and yourself. In case of doubt, that is what the `☐ Helpless` option is used for.
- http://www.opencollar.at/relay.html
- http://www.opencollar.at/contact.html
