### ISSUE TITLE
Looks Menu Inaccessible

### ISSUE THREAD

**Issue by dragon-architect** [OpenCollar/opencollar#999]
The Looks menu where I can edit colors, glow, shiny, texture, themes, etc. on the elements of my collars is currently inaccessible via the main menu.

Current main menu navigation: `Collar Menu > Settings > Themes`

Returns error in chat:
```
Collar: This collar has no themes installed.
You can type "<prefix> looks" to fine-tune your collar
(NOTE: Basic building knowledge required.)
```

Currently the only way to access the Looks menu is through `<prefix> looks` in chat. Would be nice if the navigation could be updated to: `Collar Menu > Settings > Looks`

There is already a Themes button in the Looks menu, so having only a Themes button in Settings and no way to get to the Looks menu where one can customize the look of their collar is... not ideal.

(Of note: My collar was recently transmuted from 3.5 to 6.4, and the looks menu was easily accessible via the 3.5 menu. 6.4 utterly confused me when I couldn't find this menu to readjust my collar's appearance, and I spent a very long time trying to manually transfer 3.5 appearance scripts into my 6.4 collar, only to find the feature still existed through this unintuitive chat error. Please consider making the looks menu easily accessible again.)

Additional note: There is no documentation regarding how themes work for OC 6. How to create, save, load, etc.

**Comment by WendyStarfall** [comment]
Whether the settings menu of any particular artwork features a 'Looks' or a 'Themes' button is up to the supplier of the collar and can be (like any other out-of-the-box particularity) pre-configured as a setting.

What you are receiving in the Nearby Chat is a helpful notify. Not an error. Here is a definition of 'error':

> > ## error
> > 
> > _noun_  |  er·ror  |  \ˈer-ər, ˈe-rər\
> > 
> > **Simple Definition of error:**
> > 
> > : something that is not correct : a wrong action or statement
> > : a mistake made by a person who is playing a sport (such as baseball or tennis)
> > 
> > _Source: Merriam-Webster's Learner's Dictionary_

We like to use 'github issues' for our ideas and to document our work. Providing individual support for users exceeds this purpose. Please contact the supplier of your collar and ask them for a variation that's configured to your satisfaction. 'Transmuters' that build version 6.4 haven't been shipped at the time of this writing.
